<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.fdc.contract.client</package>
    <name>ContractResource</name>
    <alias>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.fdc.contract.client.ContractResource</className>
    <resourceItems>
        <resourceItem>
            <name>ContractBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>allContractType</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[allContractType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isLonelyCal</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[isLonelyCal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>amountWithOutCost</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[amountWithOutCost].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mainContractNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mainContractNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mainContractName</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mainContractName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectProjPls</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjPls].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectProjLeafPls</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjLeafPls].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectProjPls2</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjPls2].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForUnAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForUnAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractChangeBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractChangeBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>oprateOK</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[oprateOK].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>tblDetailConstraints</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[tblDetailConstraints].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>tblContractPlanConstraints</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[tblContractPlanConstraints].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractWithoutTextQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractWithoutTextQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>needCostcenter</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[needCostcenter].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PayRequestBillQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[PayRequestBillQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cantEdit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantEdit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>exist_ref</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[exist_ref].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cantRemove</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantRemove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>noContent</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[noContent].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasContent</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasContent].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasFinalSettle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasFinalSettle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRow</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForApportion</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForApportion].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>costSplitAmountLimit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitAmountLimit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>costSplitNoApportionType</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitNoApportionType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>costSplitNoApportionObject</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitNoApportionObject].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplitQueryF7WindowTitle</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplitQueryF7WindowTitle].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>contract</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contract].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>noRemove</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[noRemove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectContrTypeForCodingRule</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectContrTypeForCodingRule].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForCancel</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForCancel].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForCancelCancel</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForCancelCancel].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectRightRowForConMove</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForConMove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>oldRespDupWithNew</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[oldRespDupWithNew].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasNotSettled</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasNotSettled].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>spltedWarningForAmtChg</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[spltedWarningForAmtChg].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasSettNotNewChange</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasSettNotNewChange].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>remark</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[remark].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>splitedNotChangeIsCSplit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[splitedNotChangeIsCSplit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>stampNotMatchAmt</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[stampNotMatchAmt].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>readFileError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[readFileError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>contractRefByOtherCon</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contractRefByOtherCon].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NotEntryCost</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[NotEntryCost].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>label46</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[label46].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>label47</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[label47].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractF7Query</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractF7Query].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cantUnAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantUnAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NoPermission</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[NoPermission].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>budgetNotEnoughOrNo</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[budgetNotEnoughOrNo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>conPayPlanNotEnoughOrNo</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conPayPlanNotEnoughOrNo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>conPayPlanBalance</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conPayPlanBalance].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>reqAmtThis</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[reqAmtThis].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>costAccount</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costAccount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>balance</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[balance].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>reqAmt</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[reqAmt].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>continue</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[continue].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cantLessZero</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantLessZero].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mustAddMainNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mustAddMainNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>prjHasClosed</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[prjHasClosed].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>saveContract</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[saveContract].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>cantLessActPay</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantLessActPay].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>contractWithoutTextHasNOPayment</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contractWithoutTextHasNOPayment].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>plsSelectPartBFirst</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[plsSelectPartBFirst].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>conDtlCantEmpty</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conDtlCantEmpty].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCostCenterNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCostCenterNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCurProjectCodingNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCurProjectCodingNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractCodingNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractCodingNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fName</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fNameNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNameNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCurrencyNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurrencyNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCompensationTypeNameL2</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCompensationTypeNameL2].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fDeductMode</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fDeductMode].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fMoneyDes</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fMoneyDes].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fBreachFaichDes</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fBreachFaichDes].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasContractChangeBill</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasContractChangeBill].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCompensationAccording</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCompensationAccording].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fOtherDes</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOtherDes].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fOriginalAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOriginalAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fOriginalAmountNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOriginalAmountNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreatorNameL2</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL2].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreatorNameL2NotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL2NotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreateTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreateTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fAuditorNameL2</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL2].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_NOTNULL</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_NOTNULL].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCurProjectCodingNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractCodingNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fAuditorNameL21</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL21].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fAuditorNameL2NotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL2NotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fAuditTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fState</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fState].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fDeductMode1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fDeductMode1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreatorNameL21</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL21].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fExRate10</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fExRate10].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCurProjectLongNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectLongNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fSettlementBillNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fSettlementBillNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fAuditorNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCreateTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCreateTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCurProjectLongNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectLongNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fSettlementBillNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fSettlementBillNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fAuditorNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fAuditorNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fAuditTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fState</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fState].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCreatorNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCreatorNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCurProjectCodingNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectCodingNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCostAccountNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCostAccountNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysContractPrice</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysContractPrice].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysContractPriceNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysContractPriceNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysChangeAmt</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysChangeAmt].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysChangeAmtNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysChangeAmtNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysSplitScale</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysSplitScale].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysSplitScaleNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysSplitScaleNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysAmountNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysAmountNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysGrtSplitAmt</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysGrtSplitAmt].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fEntrysGrtSplitAmtNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysGrtSplitAmtNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_fCostAccountNumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCostAccountNumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_getIdFromNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_getIdFromNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_strTOnumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_strTOnumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SettlementCostSplit_Import_strTOnumber1</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_strTOnumber1].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fStateLen40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fStateLen40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fGetFeeCriteriaLen40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fGetFeeCriteriaLen40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fInfoPriceLen40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fInfoPriceLen40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fBizDateNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fBizDateNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fQualityTimeLen40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fQualityTimeLen40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_FOrgUnitLongNumberNotE</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_FOrgUnitLongNumberNotE].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreatorNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_CheckDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_CheckDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractChangeNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractChangeNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreatorNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCreateTimeNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreateTimeNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractChangeNumberNotE</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractChangeNumberNotE].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCurProjectCodingNumber2NotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber2NotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fEntryscostAccountNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntryscostAccountNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fEntryscostAccountNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntryscostAccountNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fEntrysParentSplitScale</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntrysParentSplitScale].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractOriginalAmountiszreo</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractOriginalAmountiszreo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>orgunitisnotexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[orgunitisnotexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>xxdybmhxxnrmzbdy</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[xxdybmhxxnrmzbdy].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mywglxdhtdyxxbm</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mywglxdhtdyxxbm].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>hasChangeAuditBill</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasChangeAuditBill].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].alias">
            <lang locale="zh_CN" value="" />
            <lang locale="zh_TW" value="null" />
            <lang locale="en_US" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].description">
            <lang locale="zh_CN" value="" />
            <lang locale="zh_TW" value="null" />
            <lang locale="en_US" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractBillQueryF7WindowTitle].value">
            <lang locale="zh_CN" value="合同单据" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="合同單據" />
            <lang locale="zh_TW" value="合同單據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractChangeBillQueryF7WindowTitle].value">
            <lang locale="zh_CN" value="变更指令单" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="變更指令單" />
            <lang locale="zh_TW" value="變更指令單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractF7Query].value">
            <lang locale="zh_CN" value="合同及无文本合同查询" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同及無文本合同查詢" />
            <lang locale="zh_TW" value="合同及無文本合同查詢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractOriginalAmountiszreo].value">
            <lang locale="zh_CN" value="合同原币金额为0，不能反算" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同原幣金額為0，不能反算" />
            <lang locale="zh_TW" value="合同原幣金額為0，不能反算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[ContractWithoutTextQueryF7WindowTitle].value">
            <lang locale="zh_CN" value="无文本合同" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="無文本合同" />
            <lang locale="zh_TW" value="無文本合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_CheckDate].value">
            <lang locale="zh_CN" value="日期格式不正确！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="日期格式不正確！" />
            <lang locale="zh_TW" value="日期格式不正確！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_FOrgUnitLongNumberNotE].value">
            <lang locale="zh_CN" value="组织长编码在工程项目所对应的成本中心不存在!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織長編碼在工程項目所對應的成本中心不存在!" />
            <lang locale="zh_TW" value="組織長編碼在工程項目所對應的成本中心不存在!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_NOTNULL].value">
            <lang locale="zh_CN" value="在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在系統中不存在！" />
            <lang locale="zh_TW" value="在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditTime].value">
            <lang locale="zh_CN" value="在已审批状态下的审批日期字段不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在已審批狀態下的審批日期字段不能為空！" />
            <lang locale="zh_TW" value="在已審批狀態下的審批日期字段不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL21].value">
            <lang locale="zh_CN" value="审批人编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批人編碼" />
            <lang locale="zh_TW" value="審批人編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL2NotNull].value">
            <lang locale="zh_CN" value="在已审批状态下的审批人字段不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在已審批狀態下的審批人字段不能為空！" />
            <lang locale="zh_TW" value="在已審批狀態下的審批人字段不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fAuditorNameL2].value">
            <lang locale="zh_CN" value="审批人编码字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批人編碼字段長度不能超過40！" />
            <lang locale="zh_TW" value="審批人編碼字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fBizDateNotNull].value">
            <lang locale="zh_CN" value="业务日期不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="業務日期不能為空！" />
            <lang locale="zh_TW" value="業務日期不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fBreachFaichDes].value">
            <lang locale="zh_CN" value="违约描述字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="違約描述字段長度不能超過40！" />
            <lang locale="zh_TW" value="違約描述字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCompensationAccording].value">
            <lang locale="zh_CN" value="违约依据字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="違約依據字段長度不能超過40！" />
            <lang locale="zh_TW" value="違約依據字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCompensationTypeNameL2].value">
            <lang locale="zh_CN" value="违约类型字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="違約類型字段長度不能超過40！" />
            <lang locale="zh_TW" value="違約類型字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractChangeNumberNotE].value">
            <lang locale="zh_CN" value="变更指令单编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更指令單編碼在系統中不存在！" />
            <lang locale="zh_TW" value="變更指令單編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractChangeNumberNotNull].value">
            <lang locale="zh_CN" value="变更指令单编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更指令單編碼不能為空！" />
            <lang locale="zh_TW" value="變更指令單編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumber1].value">
            <lang locale="zh_CN" value="该合同编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該合同編碼" />
            <lang locale="zh_TW" value="該合同編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumberNotNull].value">
            <lang locale="zh_CN" value="合同编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼不能為空！" />
            <lang locale="zh_TW" value="合同編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fContractCodingNumber].value">
            <lang locale="zh_CN" value="合同编码字段长度不能超过80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼字段長度不能超過80！" />
            <lang locale="zh_TW" value="合同編碼字段長度不能超過80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCostCenterNumber].value">
            <lang locale="zh_CN" value="组织编码字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼字段長度不能超過40！" />
            <lang locale="zh_TW" value="組織編碼字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreateTimeNotNull].value">
            <lang locale="zh_CN" value="拆分时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分時間不能為空！" />
            <lang locale="zh_TW" value="拆分時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreateTime].value">
            <lang locale="zh_CN" value="制单时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單時間不能為空！" />
            <lang locale="zh_TW" value="制單時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL21].value">
            <lang locale="zh_CN" value="该制单人编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該制單人編碼" />
            <lang locale="zh_TW" value="該制單人編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL2NotNull].value">
            <lang locale="zh_CN" value="制单人编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼不能為空！" />
            <lang locale="zh_TW" value="制單人編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNameL2].value">
            <lang locale="zh_CN" value="制单人编码字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼字段長度不能超過40！" />
            <lang locale="zh_TW" value="制單人編碼字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNumberNotNull].value">
            <lang locale="zh_CN" value="拆分人编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分人編碼不能為空！" />
            <lang locale="zh_TW" value="拆分人編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCreatorNumber].value">
            <lang locale="zh_CN" value="制单人编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼" />
            <lang locale="zh_TW" value="制單人編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber1].value">
            <lang locale="zh_CN" value="该工程项目编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該工程項目編碼" />
            <lang locale="zh_TW" value="該工程項目編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber2NotNull].value">
            <lang locale="zh_CN" value="归属财务核算对象代码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務核算對象代碼不能為空！" />
            <lang locale="zh_TW" value="歸屬財務核算對象代碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumberNotNull].value">
            <lang locale="zh_CN" value="工程项目编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼不能為空！" />
            <lang locale="zh_TW" value="工程項目編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurProjectCodingNumber].value">
            <lang locale="zh_CN" value="工程项目编码字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼字段長度不能超過40！" />
            <lang locale="zh_TW" value="工程項目編碼字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fCurrencyNumber].value">
            <lang locale="zh_CN" value="币别编码字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="幣別編碼字段長度不能超過40！" />
            <lang locale="zh_TW" value="幣別編碼字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fDeductMode1].value">
            <lang locale="zh_CN" value="扣款方式" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="扣款方式" />
            <lang locale="zh_TW" value="扣款方式" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fDeductMode].value">
            <lang locale="zh_CN" value="扣款方式字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="扣款方式字段長度不能超過40！" />
            <lang locale="zh_TW" value="扣款方式字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntrysParentSplitScale].value">
            <lang locale="zh_CN" value="拆分比例(%)应该在0~100之间" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分比例(%)應該在0~100之間" />
            <lang locale="zh_TW" value="拆分比例(%)應該在0~100之間" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntryscostAccountNumberNotNull].value">
            <lang locale="zh_CN" value="归属财务成本科目代码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務成本科目代碼不能為空！" />
            <lang locale="zh_TW" value="歸屬財務成本科目代碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fEntryscostAccountNumber].value">
            <lang locale="zh_CN" value="归属财务成本科目代码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務成本科目代碼" />
            <lang locale="zh_TW" value="歸屬財務成本科目代碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fExRate10].value">
            <lang locale="zh_CN" value="汇率录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="匯率錄入不合法！" />
            <lang locale="zh_TW" value="匯率錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fGetFeeCriteriaLen40].value">
            <lang locale="zh_CN" value="取费标准字符超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="取費標準字元超過40！" />
            <lang locale="zh_TW" value="取費標準字元超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fInfoPriceLen40].value">
            <lang locale="zh_CN" value="信息价字符超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="信息價字元超過40！" />
            <lang locale="zh_TW" value="信息價字元超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fMoneyDes].value">
            <lang locale="zh_CN" value="款项说明字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="款項說明字段長度不能超過40！" />
            <lang locale="zh_TW" value="款項說明字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNameNotNull].value">
            <lang locale="zh_CN" value="单据名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據名稱不能為空！" />
            <lang locale="zh_TW" value="單據名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fName].value">
            <lang locale="zh_CN" value="单据名称字段长度不能超过80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據名稱字段長度不能超過80！" />
            <lang locale="zh_TW" value="單據名稱字段長度不能超過80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNumberNotNull].value">
            <lang locale="zh_CN" value="单据编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據編碼不能為空！" />
            <lang locale="zh_TW" value="單據編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fNumber].value">
            <lang locale="zh_CN" value="单据编码字段长度不能超过80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據編碼字段長度不能超過80！" />
            <lang locale="zh_TW" value="單據編碼字段長度不能超過80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOriginalAmountNotNull].value">
            <lang locale="zh_CN" value="原币金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="原幣金額不能為空！" />
            <lang locale="zh_TW" value="原幣金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOriginalAmount].value">
            <lang locale="zh_CN" value="原币金额录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="原幣金額錄入不合法！" />
            <lang locale="zh_TW" value="原幣金額錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fOtherDes].value">
            <lang locale="zh_CN" value="其他说明字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="其他說明字段長度不能超過40！" />
            <lang locale="zh_TW" value="其他說明字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fQualityTimeLen40].value">
            <lang locale="zh_CN" value="保修期限字符超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="保修期限字元超過40！" />
            <lang locale="zh_TW" value="保修期限字元超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fStateLen40].value">
            <lang locale="zh_CN" value="状态字符超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="狀態字元超過40！" />
            <lang locale="zh_TW" value="狀態字元超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[Import_fState].value">
            <lang locale="zh_CN" value="状态录入无效！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="狀態錄入無效！" />
            <lang locale="zh_TW" value="狀態錄入無效！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[NoPermission].value">
            <lang locale="zh_CN" value="您没有组织:{0}的查看业务权限!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="您沒有組織:{0}的查看業務許可權!" />
            <lang locale="zh_TW" value="您沒有組織:{0}的查看業務許可權!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[NotEntryCost].value">
            <lang locale="zh_CN" value="当前单据不进入动态成本！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前單據不進入動態成本！" />
            <lang locale="zh_TW" value="當前單據不進入動態成本！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[PayRequestBillQueryF7WindowTitle].value">
            <lang locale="zh_CN" value="付款申请单" />
            <lang locale="en_US" value="null" />
            <lang locale="zh_HK" value="付款申請單" />
            <lang locale="zh_TW" value="付款申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplitQueryF7WindowTitle].value">
            <lang locale="zh_CN" value="结算成本拆分" />
            <lang locale="en_US" value="null" />
            <lang locale="zh_HK" value="結算成本拆分" />
            <lang locale="zh_TW" value="結算成本拆分" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAmount].value">
            <lang locale="zh_CN" value="已拆分结算造价" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已拆分結算造價" />
            <lang locale="zh_TW" value="已拆分結算造價" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditTime].value">
            <lang locale="zh_CN" value="在已审批状态下的审批日期字段不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在已審批狀態下的審批日期字段不能為空！" />
            <lang locale="zh_TW" value="在已審批狀態下的審批日期字段不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumber1].value">
            <lang locale="zh_CN" value="或者审批人编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="或者審批人編碼" />
            <lang locale="zh_TW" value="或者審批人編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumberNotNull].value">
            <lang locale="zh_CN" value="在已审批状态下的审批人字段不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在已審批狀態下的審批人字段不能為空！" />
            <lang locale="zh_TW" value="在已審批狀態下的審批人字段不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fAuditorNumber].value">
            <lang locale="zh_CN" value="拆分人编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分人編碼不能為空！" />
            <lang locale="zh_TW" value="拆分人編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCostAccountNumber1].value">
            <lang locale="zh_CN" value="该成本科目代码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該成本科目代碼" />
            <lang locale="zh_TW" value="該成本科目代碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCostAccountNumber].value">
            <lang locale="zh_CN" value="归属财务成本科目不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務成本科目不能為空！" />
            <lang locale="zh_TW" value="歸屬財務成本科目不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCreateTime].value">
            <lang locale="zh_CN" value="拆分时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分時間不能為空！" />
            <lang locale="zh_TW" value="拆分時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCreatorNumber].value">
            <lang locale="zh_CN" value="拆分人编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分人編碼" />
            <lang locale="zh_TW" value="拆分人編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectCodingNumber].value">
            <lang locale="zh_CN" value="归属财务核算对象不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務核算對象不能為空！" />
            <lang locale="zh_TW" value="歸屬財務核算對象不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectLongNumber1].value">
            <lang locale="zh_CN" value="该工程项目编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該工程項目編碼" />
            <lang locale="zh_TW" value="該工程項目編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fCurProjectLongNumber].value">
            <lang locale="zh_CN" value="工程项目编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼不能為空！" />
            <lang locale="zh_TW" value="工程項目編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysAmountNotNull].value">
            <lang locale="zh_CN" value="归属金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬金額不能為空！" />
            <lang locale="zh_TW" value="歸屬金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysAmount].value">
            <lang locale="zh_CN" value="归属金额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬金額" />
            <lang locale="zh_TW" value="歸屬金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysChangeAmtNotNull].value">
            <lang locale="zh_CN" value="合同变更金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同變更金額不能為空！" />
            <lang locale="zh_TW" value="合同變更金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysChangeAmt].value">
            <lang locale="zh_CN" value="合同变更金额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同變更金額" />
            <lang locale="zh_TW" value="合同變更金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysContractPriceNotNull].value">
            <lang locale="zh_CN" value="合同签约金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同簽約金額不能為空！" />
            <lang locale="zh_TW" value="合同簽約金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysContractPrice].value">
            <lang locale="zh_CN" value="合同签约金额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同簽約金額" />
            <lang locale="zh_TW" value="合同簽約金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysGrtSplitAmtNotNull].value">
            <lang locale="zh_CN" value="归属保修金金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬保修金金額不能為空！" />
            <lang locale="zh_TW" value="歸屬保修金金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysGrtSplitAmt].value">
            <lang locale="zh_CN" value="归属保修金金额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬保修金金額" />
            <lang locale="zh_TW" value="歸屬保修金金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysSplitScaleNotNull].value">
            <lang locale="zh_CN" value="拆分比例(%)不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分比例(%)不能為空！" />
            <lang locale="zh_TW" value="拆分比例(%)不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fEntrysSplitScale].value">
            <lang locale="zh_CN" value="录入的拆分比例(%)不在0~100之间！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="錄入的拆分比例(%)不在0~100之間！" />
            <lang locale="zh_TW" value="錄入的拆分比例(%)不在0~100之間！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fSettlementBillNumber1].value">
            <lang locale="zh_CN" value="该结算单编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該結算單編碼" />
            <lang locale="zh_TW" value="該結算單編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fSettlementBillNumber].value">
            <lang locale="zh_CN" value="结算单编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="結算單編碼不能為空！" />
            <lang locale="zh_TW" value="結算單編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_fState].value">
            <lang locale="zh_CN" value="状态" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="狀態" />
            <lang locale="zh_TW" value="狀態" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_getIdFromNumber].value">
            <lang locale="zh_CN" value="对象找不到！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="對象找不到！" />
            <lang locale="zh_TW" value="對象找不到！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_strTOnumber1].value">
            <lang locale="zh_CN" value="应该录入数字型！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="應該錄入數字型！" />
            <lang locale="zh_TW" value="應該錄入數字型！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[SettlementCostSplit_Import_strTOnumber].value">
            <lang locale="zh_CN" value="必须以 1－17 位整数或加 1－2位小数构成！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="必須以 1－17 位整數或加 1－2位小數構成！" />
            <lang locale="zh_TW" value="必須以 1－17 位整數或加 1－2位小數構成！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[allContractType].value">
            <lang locale="zh_CN" value="所有合同" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="所有合同" />
            <lang locale="zh_TW" value="所有合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[amountWithOutCost].value">
            <lang locale="zh_CN" value="补充合同金额" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="補充合同金額" />
            <lang locale="zh_TW" value="補充合同金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[balance].value">
            <lang locale="zh_CN" value="余额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="餘額" />
            <lang locale="zh_TW" value="餘額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[budgetNotEnoughOrNo].value">
            <lang locale="zh_CN" value="预算余额不足或没有预算!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="預算餘額不足或沒有預算!" />
            <lang locale="zh_TW" value="預算餘額不足或沒有預算!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantEdit].value">
            <lang locale="zh_CN" value="您当前选择的单据的状态不适合修改操作" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="您當前選擇的單據的狀態不適合修改操作" />
            <lang locale="zh_TW" value="您當前選擇的單據的狀態不適合修改操作" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantLessActPay].value">
            <lang locale="zh_CN" value="合同修订金额不能小于合同实付款！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同修訂金額不能小於合同實付款！" />
            <lang locale="zh_TW" value="合同修訂金額不能小於合同實付款！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantLessZero].value">
            <lang locale="zh_CN" value="修订后原币金额不能小于0！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="修訂後原幣金額不能小於0！" />
            <lang locale="zh_TW" value="修訂後原幣金額不能小於0！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantRemove].value">
            <lang locale="zh_CN" value="您所选择的记录中，存在状态不适合删除的单据，请重新选择" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="您所選擇的記錄中，存在狀態不適合刪除的單據，請重新選擇" />
            <lang locale="zh_TW" value="您所選擇的記錄中，存在狀態不適合刪除的單據，請重新選擇" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[cantUnAudit].value">
            <lang locale="zh_CN" value="付款单已经被拆分，不能反审批" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="付款單已經被拆分，不能反審批" />
            <lang locale="zh_TW" value="付款單已經被拆分，不能反審批" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conDtlCantEmpty].value">
            <lang locale="zh_CN" value="合同详细信息中的{0}的{1}不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同詳細信息中的{0}的{1}不能為空！" />
            <lang locale="zh_TW" value="合同詳細信息中的{0}的{1}不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conPayPlanBalance].value">
            <lang locale="zh_CN" value="合同付款计划余额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同付款計畫餘額" />
            <lang locale="zh_TW" value="合同付款計畫餘額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[conPayPlanNotEnoughOrNo].value">
            <lang locale="zh_CN" value="没有合同付款计划或者合同付款计划余额不足!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="沒有合同付款計畫或者合同付款計畫餘額不足!" />
            <lang locale="zh_TW" value="沒有合同付款計畫或者合同付款計畫餘額不足!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[continue].value">
            <lang locale="zh_CN" value="是否继续" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否繼續" />
            <lang locale="zh_TW" value="是否繼續" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contractRefByOtherCon].value">
            <lang locale="zh_CN" value="您所选择的记录中，存在被补充/三方合同引用的情况，请先删除补充/三方合同" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="您所選擇的記錄中，存在被補充/三方合同引用的情況，請先刪除補充/三方合同" />
            <lang locale="zh_TW" value="您所選擇的記錄中，存在被補充/三方合同引用的情況，請先刪除補充/三方合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contractWithoutTextHasNOPayment].value">
            <lang locale="zh_CN" value="该无文本合同没有对应的付款单" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="該無文本合同沒有對應的付款單" />
            <lang locale="zh_TW" value="該無文本合同沒有對應的付款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[contract].value">
            <lang locale="zh_CN" value="合同" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同" />
            <lang locale="zh_TW" value="合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costAccount].value">
            <lang locale="zh_CN" value="成本科目" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="成本科目" />
            <lang locale="zh_TW" value="成本科目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitAmountLimit].value">
            <lang locale="zh_CN" value="合同拆分金额不能大于合同造价！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同拆分金額不能大於合同造價！" />
            <lang locale="zh_TW" value="合同拆分金額不能大於合同造價！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitNoApportionObject].value">
            <lang locale="zh_CN" value="没有选择分摊对象" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="沒有選擇分攤對象" />
            <lang locale="zh_TW" value="沒有選擇分攤對象" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[costSplitNoApportionType].value">
            <lang locale="zh_CN" value="没有选择分摊类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="沒有選擇分攤類型" />
            <lang locale="zh_TW" value="沒有選擇分攤類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[exist_ref].value">
            <lang locale="zh_CN" value="您所选择的记录中，存在有关联单据的情况，无法完成您请求的操作" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="您所選擇的記錄中，存在有關聯單據的情況，無法完成您請求的操作" />
            <lang locale="zh_TW" value="您所選擇的記錄中，存在有關聯單據的情況，無法完成您請求的操作" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasChangeAuditBill].value">
            <lang locale="zh_CN" value="合同已关联变更审批单，不允许此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同已關聯變更審批單，不允許此操作！" />
            <lang locale="zh_TW" value="合同已關聯變更審批單，不允許此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasContent].value">
            <lang locale="zh_CN" value="已经有正文,是否替换?" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已經有正文,是否替換?" />
            <lang locale="zh_TW" value="已經有正文,是否替換?" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasContractChangeBill].value">
            <lang locale="zh_CN" value="合同已关联变更指令单，不允许此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同已關聯變更指令單，不允許此操作！" />
            <lang locale="zh_TW" value="合同已關聯變更指令單，不允許此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasFinalSettle].value">
            <lang locale="zh_CN" value="当前合同已有最终结算，不能新增结算单" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前合同已有最終結算，不能新增結算單" />
            <lang locale="zh_TW" value="當前合同已有最終結算，不能新增結算單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasNotSettled].value">
            <lang locale="zh_CN" value="合同尚未结算,不能终止" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同尚未結算,不能終止" />
            <lang locale="zh_TW" value="合同尚未結算,不能終止" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[hasSettNotNewChange].value">
            <lang locale="zh_CN" value="该合同已经结算，不能新增变更指令单" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該合同已經結算，不能新增變更指令單" />
            <lang locale="zh_TW" value="該合同已經結算，不能新增變更指令單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[isLonelyCal].value">
            <lang locale="zh_CN" value="是否单独核算" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="是否單獨核算" />
            <lang locale="zh_TW" value="是否單獨核算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[label46].value">
            <lang locale="zh_CN" value="启用成本财务一体化" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="啟用成本財務一體化" />
            <lang locale="zh_TW" value="啟用成本財務一體化" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[label47].value">
            <lang locale="zh_CN" value="合同可进行多次结算" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同可進行多次結算" />
            <lang locale="zh_TW" value="合同可進行多次結算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mainContractName].value">
            <lang locale="zh_CN" value="对应主合同名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="對應主合同名稱" />
            <lang locale="zh_TW" value="對應主合同名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mainContractNumber].value">
            <lang locale="zh_CN" value="对应主合同编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="對應主合同編碼" />
            <lang locale="zh_TW" value="對應主合同編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mustAddMainNumber].value">
            <lang locale="zh_CN" value="补充合同必须录入主合同编码(在合同详细信息中录入)" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="補充合同必須錄入主合同編碼(在合同詳細信息中錄入)" />
            <lang locale="zh_TW" value="補充合同必須錄入主合同編碼(在合同詳細信息中錄入)" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[mywglxdhtdyxxbm].value">
            <lang locale="zh_CN" value="没有为该类型的合同定义详细信息" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="沒有為該類型的合同定義詳細信息" />
            <lang locale="zh_TW" value="沒有為該類型的合同定義詳細信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[needCostcenter].value">
            <lang locale="zh_CN" value="当前组织不是成本中心，请设置为成本中心" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前組織不是成本中心，請設置為成本中心" />
            <lang locale="zh_TW" value="當前組織不是成本中心，請設置為成本中心" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[noContent].value">
            <lang locale="zh_CN" value="合同没有上传正文!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同沒有上傳正文!" />
            <lang locale="zh_TW" value="合同沒有上傳正文!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[noRemove].value">
            <lang locale="zh_CN" value="当前单据不适合删除操作！" />
            <lang locale="en_US" value="" />
            <lang locale="zh_HK" value="當前單據不適合刪除操作！" />
            <lang locale="zh_TW" value="當前單據不適合刪除操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[oldRespDupWithNew].value">
            <lang locale="zh_CN" value="责任人和责任部门不能与合同的原责任人和责任部门相同" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="責任人和責任部門不能與合同的原責任人和責任部門相同" />
            <lang locale="zh_TW" value="責任人和責任部門不能與合同的原責任人和責任部門相同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[oprateOK].value">
            <lang locale="zh_CN" value="操作成功" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="操作成功" />
            <lang locale="zh_TW" value="操作成功" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[orgunitisnotexist].value">
            <lang locale="zh_CN" value="组织编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼在系統中不存在！" />
            <lang locale="zh_TW" value="組織編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[plsSelectPartBFirst].value">
            <lang locale="zh_CN" value="请先录入合同乙方后方可选择主合同！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請先錄入合同乙方後方可選擇主合同！" />
            <lang locale="zh_TW" value="請先錄入合同乙方後方可選擇主合同！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[prjHasClosed].value">
            <lang locale="zh_CN" value="该合同所在的工程项目已经处于关闭状态，不能进入动态成本，请取消\&quot;进入动态成本\&quot;的选择再保存/提交" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該合同所在的工程項目已經處於關閉狀態，不能進入動態成本，請取消\&quot;進入動態成本\&quot;的選擇再保存/提交" />
            <lang locale="zh_TW" value="該合同所在的工程項目已經處於關閉狀態，不能進入動態成本，請取消\&quot;進入動態成本\&quot;的選擇再保存/提交" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[readFileError].value">
            <lang locale="zh_CN" value="读文件错误" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="讀文件錯誤" />
            <lang locale="zh_TW" value="讀文件錯誤" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[remark].value">
            <lang locale="zh_CN" value="备注" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="備註" />
            <lang locale="zh_TW" value="備註" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[reqAmtThis].value">
            <lang locale="zh_CN" value="本次申请金额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="本次申請金額" />
            <lang locale="zh_TW" value="本次申請金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[reqAmt].value">
            <lang locale="zh_CN" value="申请额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="申請額" />
            <lang locale="zh_TW" value="申請額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[saveContract].value">
            <lang locale="zh_CN" value="合同还未保存，请先保存合同，再维护合同付款计划" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同還未保存，請先保存合同，再維護合同付款計畫" />
            <lang locale="zh_TW" value="合同還未保存，請先保存合同，再維護合同付款計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectContrTypeForCodingRule].value">
            <lang locale="zh_CN" value="请选择合同类型明细节点,因为编码规则中定义了合同类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇合同類型明細節點,因為編碼規則中定義了合同類型" />
            <lang locale="zh_TW" value="請選擇合同類型明細節點,因為編碼規則中定義了合同類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjLeafPls].value">
            <lang locale="zh_CN" value="请选择工程项目明细节点" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇工程項目明細節點" />
            <lang locale="zh_TW" value="請選擇工程項目明細節點" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjPls2].value">
            <lang locale="zh_CN" value="请选择工程项目节点（非公司，如果没有工程项目，请先增加工程项目）" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇工程項目節點（非公司，如果沒有工程項目，請先增加工程項目）" />
            <lang locale="zh_TW" value="請選擇工程項目節點（非公司，如果沒有工程項目，請先增加工程項目）" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectProjPls].value">
            <lang locale="zh_CN" value="请选择工程项目" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇工程項目" />
            <lang locale="zh_TW" value="請選擇工程項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForApportion].value">
            <lang locale="zh_CN" value="当前分录无法设置所选择类型的分摊方案！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前分錄無法設置所選擇類型的分攤方案！" />
            <lang locale="zh_TW" value="當前分錄無法設置所選擇類型的分攤方案！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForAudit].value">
            <lang locale="zh_CN" value="存在不符合审批条件的记录，请重新选择，保证所选的记录都是提交状态的" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在不符合審批條件的記錄，請重新選擇，保證所選的記錄都是提交狀態的" />
            <lang locale="zh_TW" value="存在不符合審批條件的記錄，請重新選擇，保證所選的記錄都是提交狀態的" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForCancelCancel].value">
            <lang locale="zh_CN" value="存在不符合生效条件的记录，请重新选择，保证所选的记录都是作废状态的" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在不符合生效條件的記錄，請重新選擇，保證所選的記錄都是作廢狀態的" />
            <lang locale="zh_TW" value="存在不符合生效條件的記錄，請重新選擇，保證所選的記錄都是作廢狀態的" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForCancel].value">
            <lang locale="zh_CN" value="存在不符合终止条件的记录，请重新选择，保证所选的记录都是已审批状态的" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在不符合終止條件的記錄，請重新選擇，保證所選的記錄都是已審批狀態的" />
            <lang locale="zh_TW" value="存在不符合終止條件的記錄，請重新選擇，保證所選的記錄都是已審批狀態的" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForConMove].value">
            <lang locale="zh_CN" value="当前记录不是已审批的，不能交底，请重新选择" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前記錄不是已審批的，不能交底，請重新選擇" />
            <lang locale="zh_TW" value="當前記錄不是已審批的，不能交底，請重新選擇" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRowForUnAudit].value">
            <lang locale="zh_CN" value="存在不符合反审批条件的记录，请重新选择，保证所选的记录都是已审批状态的。" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在不符合反審批條件的記錄，請重新選擇，保證所選的記錄都是已審批狀態的。" />
            <lang locale="zh_TW" value="存在不符合反審批條件的記錄，請重新選擇，保證所選的記錄都是已審批狀態的。" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[selectRightRow].value">
            <lang locale="zh_CN" value="存在不符合条件的记录，请重新选择" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在不符合條件的記錄，請重新選擇" />
            <lang locale="zh_TW" value="存在不符合條件的記錄，請重新選擇" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[splitedNotChangeIsCSplit].value">
            <lang locale="zh_CN" value="该合同已经拆分，不能修改此属性" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該合同已經拆分，不能修改此屬性" />
            <lang locale="zh_TW" value="該合同已經拆分，不能修改此屬性" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[spltedWarningForAmtChg].value">
            <lang locale="zh_CN" value="如果该合同已经拆分，修改金额会导致合同金额与拆分不一致，修改金额后，将作废拆分，如果已经有付款拆分/结算拆分，将作废付款拆分/结算拆分" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="如果該合同已經拆分，修改金額會導致合同金額與拆分不一致，修改金額後，將作廢拆分，如果已經有付款拆分/結算拆分，將作廢付款拆分/結算拆分" />
            <lang locale="zh_TW" value="如果該合同已經拆分，修改金額會導致合同金額與拆分不一致，修改金額後，將作廢拆分，如果已經有付款拆分/結算拆分，將作廢付款拆分/結算拆分" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[stampNotMatchAmt].value">
            <lang locale="zh_CN" value="印花税金额 与 合同金额*印花税率 不等，是否继续？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="印花稅金額 與 合同金額*印花稅率 不等，是否繼續？" />
            <lang locale="zh_TW" value="印花稅金額 與 合同金額*印花稅率 不等，是否繼續？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[tblContractPlanConstraints].value">
            <lang locale="zh_CN" value="合同计划" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同計畫" />
            <lang locale="zh_TW" value="合同計畫" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[tblDetailConstraints].value">
            <lang locale="zh_CN" value="合同详细信息" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同詳細信息" />
            <lang locale="zh_TW" value="合同詳細信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.client.ContractResource].resourceItems.resourceItem[xxdybmhxxnrmzbdy].value">
            <lang locale="zh_CN" value="填写的详细定义编码和详细内容不能对应！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="填寫的詳細定義編碼和詳細內容不能對應！" />
            <lang locale="zh_TW" value="填寫的詳細定義編碼和詳細內容不能對應！" />
        </rs>
    </resource>
</i18nResource>

