<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.fdc.contract</package>
    <name>ContractTransmissionResource</name>
    <alias>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.fdc.contract.ContractTransmissionResource</className>
    <resourceItems>
        <resourceItem>
            <name>CurProjectLongNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectLongNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractCodingNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractCodingNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NameNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OriginalAmountNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>IsGuerdoned</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[IsGuerdoned].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorTimeNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorTimeNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>State</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[State].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostOrgLongNumberIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostOrgLongNumberIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurProjectLongNumberIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectLongNumberIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractCodingNumberIsOver80</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractCodingNumberIsOver80].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NumberIsOver80</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumberIsOver80].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NameIsOver80</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameIsOver80].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>StateIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[StateIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurrencyNumberIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNumberIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GuerdonThingsIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GuerdonThingsIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GuerdonDesIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GuerdonDesIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PutOutTypeIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OriginalAmountIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNumberIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditorNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTimeNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditorNumberIsOver40</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberIsOver40].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditorNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurProjectNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractBillNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractBillNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurrencyNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OrgUnitNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreateTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurProjectCodingNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectCodingNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostAccountNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostAccountNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SplitScaleNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SplitScaleNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AmountNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AmountNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostSplitTypeEnum</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostSplitTypeEnum].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Amount</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Amount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostAccountNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostAccountNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProductTypeNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProductTypeNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>IsConfirm</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[IsConfirm].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_ChangeAuditNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fNumberIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fNumberIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_SeqIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_SeqIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fSeqIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fSeqIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_ChangeContentIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeContentIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_ChangeContentIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeContentIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Yes</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Yes].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>No</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[No].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_ChangeAuditNumberIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_ChangeAuditNumberIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_SeqIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_SeqIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fMainSuppNameIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fMainSuppNameIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fMainSuppNameIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fMainSuppNameIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fContentSeqIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fContentSeqIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fCostAmountIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostAmountIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fReckonorNameIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fReckonorNameIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fDutyOrgNameIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDutyOrgNameIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fDutyOrgNameIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDutyOrgNameIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractBillCodingNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractBillCodingNumberIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fContractBillCodingNumberIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostCenterNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostCenterNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PutOutTypeNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PutOutTypeIsError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeIsError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CurrencyNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ExchangeNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ExchangeNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OriginalAmountNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ExRateNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ExRateNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AmountNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AmountNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntrysSplitScaleNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntrysSplitScaleNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntrysAmountNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntrysAmountNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>curProjectInfo</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[curProjectInfo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntryIsRepeat</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntryIsRepeat].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OrgUnitNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OrgUnitNumberIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProjectNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProjectNumberIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FNumberIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNumberIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FNumberIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNumberIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FNameIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNameIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FNameIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNameIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BizDateIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BizDateIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BizDateFormatError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BizDateFormatError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTypeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTypeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChangeReasonIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeReasonIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>JobTypeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[JobTypeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChangeSubjectIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeSubjectIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConductDeptIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductDeptIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SpecialtyTypeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SpecialtyTypeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UrgentDegreeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegreeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConstrSiteIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConstrSiteIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ReaDescIsLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ReaDescIsLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>InvailCostIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[InvailCostIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreateTimeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreateTimeFormatError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeFormatError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditorIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTimeIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTimeFormatError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeFormatError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConductUnitIsNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductUnitIsNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntityStatusYes</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntityStatusYes].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>EntityStatusNo</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntityStatusNo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GraphCount_ElectFile</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_ElectFile].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GraphCount_PaperFile</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_PaperFile].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GraphCount_NoFile</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_NoFile].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>GraphCountOutside</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCountOutside].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_SAVED</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_SAVED].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_SUBMITTED</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_SUBMITTED].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_ANNOUNCE</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_ANNOUNCE].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_VISA</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_VISA].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_CANCEL</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_CANCEL].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillState_AUDITTED</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_AUDITTED].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>FDCBillStateOutSide</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillStateOutSide].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UrgentDegree_Urgent</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegree_Urgent].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UrgentDegree_Normal</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegree_Normal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UrgentDegreeOutSide</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegreeOutSide].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OrgUnitNumberNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ProjectNumberNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTypeNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTypeNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ChangeReasonNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeReasonNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>JobTypeNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[JobTypeNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConductDeptNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductDeptNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>SpecialtyTypeNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SpecialtyTypeNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>OfferOutside</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OfferOutside].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Offer_SelfCom</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_SelfCom].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Offer_DesignCom</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_DesignCom].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Offer_ConstrParty</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_ConstrParty].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Offer_Superviser</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_Superviser].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ConductUnitNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductUnitNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>UserNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UserNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BillNumberExist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BillNumberExist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>BillNameExist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BillNameExist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreatorNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditorNonexist</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNonexist].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fCostDescriptionIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostDescriptionIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fBalanceTypeIsTooLong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fBalanceTypeIsTooLong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NumbeIsRepate</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumbeIsRepate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NameIsRepate</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameIsRepate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fCostAmountIsOverLength</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostAmountIsOverLength].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fDeductAmountIsOverLength</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDeductAmountIsOverLength].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fConstructPriceIsOverLength</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fConstructPriceIsOverLength].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>PriceIsOverLenth</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PriceIsOverLenth].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AllSplit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AllSplit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreateTimeError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AuditTimeError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CreateDateError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateDateError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fCopySuppNameIsNotExsit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCopySuppNameIsNotExsit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>splitScaleError</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[splitScaleError].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostOrgLongNumberNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostOrgLongNumberNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostNouseIsWrong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostNouseIsWrong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>CostNousePriceIsNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostNousePriceIsNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCostAmountIsWrong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fCostAmountIsWrong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fCostAmountIsNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fCostAmountIsNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fDeductAmountIsWrong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fDeductAmountIsWrong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fDeductAmountIsNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fDeductAmountIsNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fConstructPriceIsWrong</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fConstructPriceIsWrong].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_fConstructPriceIsNotNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fConstructPriceIsNotNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>ContractByCurProjectNotFound</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractByCurProjectNotFound].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Import_StateProdsplit</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_StateProdsplit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Cash</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Cash].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>Ticket</name>
            <value>i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Ticket].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].alias">
            <lang locale="zh_CN" value="合同包资源文件" />
            <lang locale="en_US" value="null" />
            <lang locale="zh_HK" value="合同包資源文件" />
            <lang locale="zh_TW" value="合同包資源文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].description">
            <lang locale="zh_CN" value="" />
            <lang locale="zh_TW" value="null" />
            <lang locale="en_US" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AllSplit].value">
            <lang locale="zh_CN" value="合同已全部拆分！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同已全部拆分！" />
            <lang locale="zh_TW" value="合同已全部拆分！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AmountNotNull].value">
            <lang locale="zh_CN" value="归属金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬金額不能為空！" />
            <lang locale="zh_TW" value="歸屬金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AmountNotNumber].value">
            <lang locale="zh_CN" value="本位币金额必须是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="本位幣金額必須是數字！" />
            <lang locale="zh_TW" value="本位幣金額必須是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Amount].value">
            <lang locale="zh_CN" value="归属金额不能大于已拆分合同造价！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬金額不能大於已拆分合同造價！" />
            <lang locale="zh_TW" value="歸屬金額不能大於已拆分合同造價！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeError].value">
            <lang locale="zh_CN" value="审批时间格式不正确，建议格式YYYY-MM-DD！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批時間格式不正確，建議格式YYYY-MM-DD！" />
            <lang locale="zh_TW" value="審批時間格式不正確，建議格式YYYY-MM-DD！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeFormatError].value">
            <lang locale="zh_CN" value="确保审核时间格式为YYYY-MM-DD!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確保審核時間格式為YYYY-MM-DD!" />
            <lang locale="zh_TW" value="確保審核時間格式為YYYY-MM-DD!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeIsNull].value">
            <lang locale="zh_CN" value="审核时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審核時間不能為空！" />
            <lang locale="zh_TW" value="審核時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTimeNotNull].value">
            <lang locale="zh_CN" value="审批日期不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批日期不能為空！" />
            <lang locale="zh_TW" value="審批日期不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTypeIsNull].value">
            <lang locale="zh_CN" value="变更类型不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更類型不能為空！" />
            <lang locale="zh_TW" value="變更類型不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditTypeNonexist].value">
            <lang locale="zh_CN" value="变更类型在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更類型在系統中不存在！" />
            <lang locale="zh_TW" value="變更類型在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorIsNull].value">
            <lang locale="zh_CN" value="审核人不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審核人不能為空！" />
            <lang locale="zh_TW" value="審核人不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNonexist].value">
            <lang locale="zh_CN" value="审核人在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審核人在系統中不存在！" />
            <lang locale="zh_TW" value="審核人在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberIsOver40].value">
            <lang locale="zh_CN" value="审批人不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批人不能超過40個字元！" />
            <lang locale="zh_TW" value="審批人不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberNotFound].value">
            <lang locale="zh_CN" value="审批人在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批人在系統中不存在！" />
            <lang locale="zh_TW" value="審批人在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[AuditorNumberNotNull].value">
            <lang locale="zh_CN" value="审批人编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="審批人編碼不能為空！" />
            <lang locale="zh_TW" value="審批人編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BillNameExist].value">
            <lang locale="zh_CN" value="导入的单据名称已存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="導入的單據名稱已存在！" />
            <lang locale="zh_TW" value="導入的單據名稱已存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BillNumberExist].value">
            <lang locale="zh_CN" value="导入的单据编号已存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="導入的單據編號已存在！" />
            <lang locale="zh_TW" value="導入的單據編號已存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BizDateFormatError].value">
            <lang locale="zh_CN" value="确保业务日期格式为YYYY-MM-DD!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確保業務日期格式為YYYY-MM-DD!" />
            <lang locale="zh_TW" value="確保業務日期格式為YYYY-MM-DD!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[BizDateIsNull].value">
            <lang locale="zh_CN" value="业务日期不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="業務日期不能為空！" />
            <lang locale="zh_TW" value="業務日期不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Cash].value">
            <lang locale="zh_CN" value="现金 对方承担税金" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="現金 對方承擔稅金" />
            <lang locale="zh_TW" value="現金 對方承擔稅金" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeReasonIsNull].value">
            <lang locale="zh_CN" value="变更原因不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更原因不能為空！" />
            <lang locale="zh_TW" value="變更原因不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeReasonNonexist].value">
            <lang locale="zh_CN" value="变更原因在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更原因在系統中不存在！" />
            <lang locale="zh_TW" value="變更原因在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ChangeSubjectIsLong].value">
            <lang locale="zh_CN" value="变更主题长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更主題長度不能大於40！" />
            <lang locale="zh_TW" value="變更主題長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductDeptIsNull].value">
            <lang locale="zh_CN" value="提出部门不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="提出部門不能為空！" />
            <lang locale="zh_TW" value="提出部門不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductDeptNonexist].value">
            <lang locale="zh_CN" value="提出部门在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="提出部門在系統中不存在！" />
            <lang locale="zh_TW" value="提出部門在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductUnitIsNull].value">
            <lang locale="zh_CN" value="提出方为“我司”时，提出单位要求必填！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="提出方為“我司”時，提出單位要求必填！" />
            <lang locale="zh_TW" value="提出方為“我司”時，提出單位要求必填！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConductUnitNonexist].value">
            <lang locale="zh_CN" value="提出单位在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="提出單位在系統中不存在！" />
            <lang locale="zh_TW" value="提出單位在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ConstrSiteIsLong].value">
            <lang locale="zh_CN" value="施工部位长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="施工部位長度不能大於40！" />
            <lang locale="zh_TW" value="施工部位長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractBillNumberNotFound].value">
            <lang locale="zh_CN" value="合同编码在录入的工程项目下不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼在錄入的工程項目下不存在！" />
            <lang locale="zh_TW" value="合同編碼在錄入的工程項目下不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractByCurProjectNotFound].value">
            <lang locale="zh_CN" value="工程项目编码下找不到对应的合同！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼下找不到對應的合同！" />
            <lang locale="zh_TW" value="工程項目編碼下找不到對應的合同！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractCodingNumberIsOver80].value">
            <lang locale="zh_CN" value="合同编码不能超过80个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼不能超過80個字元！" />
            <lang locale="zh_TW" value="合同編碼不能超過80個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ContractCodingNumberNotNull].value">
            <lang locale="zh_CN" value="合同编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼不能為空！" />
            <lang locale="zh_TW" value="合同編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostAccountNotFound].value">
            <lang locale="zh_CN" value="归属成本科目代码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬成本科目代碼在系統中不存在！" />
            <lang locale="zh_TW" value="歸屬成本科目代碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostAccountNumberNotNull].value">
            <lang locale="zh_CN" value="归属成本科目代码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬成本科目代碼不能為空！" />
            <lang locale="zh_TW" value="歸屬成本科目代碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostCenterNotFound].value">
            <lang locale="zh_CN" value="工程项目所对应的成本中心不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目所對應的成本中心不存在！" />
            <lang locale="zh_TW" value="工程項目所對應的成本中心不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostNouseIsWrong].value">
            <lang locale="zh_CN" value="无效成本金额录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="無效成本金額錄入不合法！" />
            <lang locale="zh_TW" value="無效成本金額錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostNousePriceIsNotNumber].value">
            <lang locale="zh_CN" value="无效成本金额不是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="無效成本金額不是數字！" />
            <lang locale="zh_TW" value="無效成本金額不是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostOrgLongNumberIsOver40].value">
            <lang locale="zh_CN" value="组织编码不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼不能超過40個字元！" />
            <lang locale="zh_TW" value="組織編碼不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostOrgLongNumberNotFound].value">
            <lang locale="zh_CN" value="组织长编码在工程项目所对应的成本中心不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織長編碼在工程項目所對應的成本中心不存在！" />
            <lang locale="zh_TW" value="組織長編碼在工程項目所對應的成本中心不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CostSplitTypeEnum].value">
            <lang locale="zh_CN" value="请输入正确的归属标准！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請輸入正確的歸屬標準！" />
            <lang locale="zh_TW" value="請輸入正確的歸屬標準！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateDateError].value">
            <lang locale="zh_CN" value="制单时间格式错误，建议格式YYYY-MM-DD！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單時間格式錯誤，建議格式YYYY-MM-DD！" />
            <lang locale="zh_TW" value="制單時間格式錯誤，建議格式YYYY-MM-DD！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeError].value">
            <lang locale="zh_CN" value="拆分时间格式不正确，建议格式YYYY-MM-DD！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分時間格式不正確，建議格式YYYY-MM-DD！" />
            <lang locale="zh_TW" value="拆分時間格式不正確，建議格式YYYY-MM-DD！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeFormatError].value">
            <lang locale="zh_CN" value="确保创建时间格式为YYYY-MM-DD!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確保創建時間格式為YYYY-MM-DD!" />
            <lang locale="zh_TW" value="確保創建時間格式為YYYY-MM-DD!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTimeIsNull].value">
            <lang locale="zh_CN" value="创建时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="創建時間不能為空！" />
            <lang locale="zh_TW" value="創建時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreateTime].value">
            <lang locale="zh_CN" value="拆分时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分時間不能為空！" />
            <lang locale="zh_TW" value="拆分時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorIsNull].value">
            <lang locale="zh_CN" value="创建人不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="創建人不能為空！" />
            <lang locale="zh_TW" value="創建人不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNonexist].value">
            <lang locale="zh_CN" value="制单人在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人在系統中不存在！" />
            <lang locale="zh_TW" value="制單人在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNotFound].value">
            <lang locale="zh_CN" value="拆分人在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分人在系統中不存在！" />
            <lang locale="zh_TW" value="拆分人在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberIsNull].value">
            <lang locale="zh_CN" value="拆分人不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分人不能為空！" />
            <lang locale="zh_TW" value="拆分人不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberIsOver40].value">
            <lang locale="zh_CN" value="制单人编码不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼不能超過40個字元！" />
            <lang locale="zh_TW" value="制單人編碼不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberNotFound].value">
            <lang locale="zh_CN" value="制单人编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼在系統中不存在！" />
            <lang locale="zh_TW" value="制單人編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorNumberNotNull].value">
            <lang locale="zh_CN" value="制单人编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單人編碼不能為空！" />
            <lang locale="zh_TW" value="制單人編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CreatorTimeNotNull].value">
            <lang locale="zh_CN" value="制单时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="制單時間不能為空！" />
            <lang locale="zh_TW" value="制單時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectCodingNumberNotNull].value">
            <lang locale="zh_CN" value="归属财务核算对象代码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務核算對象代碼不能為空！" />
            <lang locale="zh_TW" value="歸屬財務核算對象代碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectLongNumberIsOver40].value">
            <lang locale="zh_CN" value="工程项目编码不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼不能超過40個字元！" />
            <lang locale="zh_TW" value="工程項目編碼不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectLongNumberNotNull].value">
            <lang locale="zh_CN" value="工程项目编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼不能為空！" />
            <lang locale="zh_TW" value="工程項目編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurProjectNumberNotFound].value">
            <lang locale="zh_CN" value="工程项目编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼在系統中不存在！" />
            <lang locale="zh_TW" value="工程項目編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNotFound].value">
            <lang locale="zh_CN" value="在币种中找不到默认币别(人民币),请联系管理员！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在幣種中找不到默認幣別(人民幣),請聯繫管理員！" />
            <lang locale="zh_TW" value="在幣種中找不到默認幣別(人民幣),請聯繫管理員！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNumberIsOver40].value">
            <lang locale="zh_CN" value="币别编码不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="幣別編碼不能超過40個字元！" />
            <lang locale="zh_TW" value="幣別編碼不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[CurrencyNumberNotFound].value">
            <lang locale="zh_CN" value="币别编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="幣別編碼在系統中不存在！" />
            <lang locale="zh_TW" value="幣別編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntityStatusNo].value">
            <lang locale="zh_CN" value="否" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="否" />
            <lang locale="zh_TW" value="否" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntityStatusYes].value">
            <lang locale="zh_CN" value="是" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是" />
            <lang locale="zh_TW" value="是" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntryIsRepeat].value">
            <lang locale="zh_CN" value="分录信息重复！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="分錄信息重複！" />
            <lang locale="zh_TW" value="分錄信息重複！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntrysAmountNotNumber].value">
            <lang locale="zh_CN" value="归属金额必须是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬金額必須是數字！" />
            <lang locale="zh_TW" value="歸屬金額必須是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[EntrysSplitScaleNotNumber].value">
            <lang locale="zh_CN" value="拆分比例必须是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分比例必須是數字！" />
            <lang locale="zh_TW" value="拆分比例必須是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ExRateNotNumber].value">
            <lang locale="zh_CN" value="汇率必须是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="匯率必須是數字！" />
            <lang locale="zh_TW" value="匯率必須是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ExchangeNotFound].value">
            <lang locale="zh_CN" value="在汇率表中找不到原币与默认币别(人民币)的兑换汇率，请联系管理员!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在匯率表中找不到原幣與默認幣別(人民幣)的兌換匯率，請聯繫管理員!" />
            <lang locale="zh_TW" value="在匯率表中找不到原幣與默認幣別(人民幣)的兌換匯率，請聯繫管理員!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillStateOutSide].value">
            <lang locale="zh_CN" value="单据状态不在系统范围内！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據狀態不在系統範圍內！" />
            <lang locale="zh_TW" value="單據狀態不在系統範圍內！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_ANNOUNCE].value">
            <lang locale="zh_CN" value="已下发" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已下發" />
            <lang locale="zh_TW" value="已下發" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_AUDITTED].value">
            <lang locale="zh_CN" value="已审批" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已審批" />
            <lang locale="zh_TW" value="已審批" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_CANCEL].value">
            <lang locale="zh_CN" value="已结算" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已結算" />
            <lang locale="zh_TW" value="已結算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_SAVED].value">
            <lang locale="zh_CN" value="保存" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="保存" />
            <lang locale="zh_TW" value="保存" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_SUBMITTED].value">
            <lang locale="zh_CN" value="已提交" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已提交" />
            <lang locale="zh_TW" value="已提交" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FDCBillState_VISA].value">
            <lang locale="zh_CN" value="已签证" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已簽證" />
            <lang locale="zh_TW" value="已簽證" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNameIsLong].value">
            <lang locale="zh_CN" value="单据名称长度不能大于80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據名稱長度不能大於80！" />
            <lang locale="zh_TW" value="單據名稱長度不能大於80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNameIsNull].value">
            <lang locale="zh_CN" value="单据名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據名稱不能為空！" />
            <lang locale="zh_TW" value="單據名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNumberIsLong].value">
            <lang locale="zh_CN" value="单据编号长度不能大于80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據編號長度不能大於80！" />
            <lang locale="zh_TW" value="單據編號長度不能大於80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[FNumberIsNull].value">
            <lang locale="zh_CN" value="单据编号不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="單據編號不能為空！" />
            <lang locale="zh_TW" value="單據編號不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCountOutside].value">
            <lang locale="zh_CN" value="附件情况不在系统范围内！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="附件情況不在系統範圍內！" />
            <lang locale="zh_TW" value="附件情況不在系統範圍內！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_ElectFile].value">
            <lang locale="zh_CN" value="电子文件" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="電子文件" />
            <lang locale="zh_TW" value="電子文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_NoFile].value">
            <lang locale="zh_CN" value="无文件" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="無文件" />
            <lang locale="zh_TW" value="無文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GraphCount_PaperFile].value">
            <lang locale="zh_CN" value="纸质文件" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="紙質文件" />
            <lang locale="zh_TW" value="紙質文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GuerdonDesIsOver40].value">
            <lang locale="zh_CN" value="奖励事由不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="獎勵事由不能超過40個字元！" />
            <lang locale="zh_TW" value="獎勵事由不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[GuerdonThingsIsOver40].value">
            <lang locale="zh_CN" value="奖励事项不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="獎勵事項不能超過40個字元！" />
            <lang locale="zh_TW" value="獎勵事項不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsNotExsit].value">
            <lang locale="zh_CN" value="该变更单编码不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該變更單編碼不存在！" />
            <lang locale="zh_TW" value="該變更單編碼不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsNull].value">
            <lang locale="zh_CN" value="变更单编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更單編碼不能為空！" />
            <lang locale="zh_TW" value="變更單編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeAuditNumberIsTooLong].value">
            <lang locale="zh_CN" value="变更单编码长度不能超过80！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更單編碼長度不能超過80！" />
            <lang locale="zh_TW" value="變更單編碼長度不能超過80！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeContentIsNull].value">
            <lang locale="zh_CN" value="变更内容不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更內容不能為空！" />
            <lang locale="zh_TW" value="變更內容不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_ChangeContentIsTooLong].value">
            <lang locale="zh_CN" value="变更内容长度不能超过160个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更內容長度不能超過160個字元！" />
            <lang locale="zh_TW" value="變更內容長度不能超過160個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_SeqIsNull].value">
            <lang locale="zh_CN" value="序列号不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="序列號不能為空！" />
            <lang locale="zh_TW" value="序列號不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_SeqIsTooLong].value">
            <lang locale="zh_CN" value="序列号长度不能超过4！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="序列號長度不能超過4！" />
            <lang locale="zh_TW" value="序列號長度不能超過4！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_StateProdsplit].value">
            <lang locale="zh_CN" value="产品拆分" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="產品拆分" />
            <lang locale="zh_TW" value="產品拆分" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fConstructPriceIsNotNumber].value">
            <lang locale="zh_CN" value="施工方报审金额不是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="施工方報審金額不是數字！" />
            <lang locale="zh_TW" value="施工方報審金額不是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fConstructPriceIsWrong].value">
            <lang locale="zh_CN" value="施工方报审金额录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="施工方報審金額錄入不合法！" />
            <lang locale="zh_TW" value="施工方報審金額錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsNotExsit].value">
            <lang locale="zh_CN" value="该合同编码不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該合同編碼不存在！" />
            <lang locale="zh_TW" value="該合同編碼不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsNull].value">
            <lang locale="zh_CN" value="合同编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼不能為空！" />
            <lang locale="zh_TW" value="合同編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fContractBillCodingNumberIsTooLong].value">
            <lang locale="zh_CN" value="合同编码长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同編碼長度不能超過40！" />
            <lang locale="zh_TW" value="合同編碼長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fCostAmountIsNotNumber].value">
            <lang locale="zh_CN" value="测算金额不是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="測算金額不是數字！" />
            <lang locale="zh_TW" value="測算金額不是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fCostAmountIsWrong].value">
            <lang locale="zh_CN" value="测算金额录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="測算金額錄入不合法！" />
            <lang locale="zh_TW" value="測算金額錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fDeductAmountIsNotNumber].value">
            <lang locale="zh_CN" value="责任扣款金额不是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="責任扣款金額不是數字！" />
            <lang locale="zh_TW" value="責任扣款金額不是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fDeductAmountIsWrong].value">
            <lang locale="zh_CN" value="责任扣款金额录入不合法！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="責任扣款金額錄入不合法！" />
            <lang locale="zh_TW" value="責任扣款金額錄入不合法！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fMainSuppNameIsNotExsit].value">
            <lang locale="zh_CN" value="该主送单位不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該主送單位不存在！" />
            <lang locale="zh_TW" value="該主送單位不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fMainSuppNameIsNull].value">
            <lang locale="zh_CN" value="主送单位不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="主送單位不能為空！" />
            <lang locale="zh_TW" value="主送單位不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fNumberIsTooLong].value">
            <lang locale="zh_CN" value="变更单编码长度不能超过160个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="變更單編碼長度不能超過160個字元！" />
            <lang locale="zh_TW" value="變更單編碼長度不能超過160個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Import_fSeqIsTooLong].value">
            <lang locale="zh_CN" value="序列号太长！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="序列號太長！" />
            <lang locale="zh_TW" value="序列號太長！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[InvailCostIsNull].value">
            <lang locale="zh_CN" value="当存在无效成本时，无效成本金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當存在無效成本時，無效成本金額不能為空！" />
            <lang locale="zh_TW" value="當存在無效成本時，無效成本金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[IsConfirm].value">
            <lang locale="zh_CN" value="请按照提示信息正确填写是否已确定！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請按照提示信息正確填寫是否已確定！" />
            <lang locale="zh_TW" value="請按照提示信息正確填寫是否已確定！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[IsGuerdoned].value">
            <lang locale="zh_CN" value="请按照提示信息正确填写是否已奖励！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請按照提示信息正確填寫是否已獎勵！" />
            <lang locale="zh_TW" value="請按照提示信息正確填寫是否已獎勵！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[JobTypeIsNull].value">
            <lang locale="zh_CN" value="承包类型不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="承包類型不能為空！" />
            <lang locale="zh_TW" value="承包類型不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[JobTypeNonexist].value">
            <lang locale="zh_CN" value="承包类型在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="承包類型在系統中不存在！" />
            <lang locale="zh_TW" value="承包類型在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameIsOver80].value">
            <lang locale="zh_CN" value="名称不能超过80个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="名稱不能超過80個字元！" />
            <lang locale="zh_TW" value="名稱不能超過80個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameIsRepate].value">
            <lang locale="zh_CN" value="名称在系统中已存在，请重新输入！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="名稱在系統中已存在，請重新輸入！" />
            <lang locale="zh_TW" value="名稱在系統中已存在，請重新輸入！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NameNotNull].value">
            <lang locale="zh_CN" value="名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="名稱不能為空！" />
            <lang locale="zh_TW" value="名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[No].value">
            <lang locale="zh_CN" value="否" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="否" />
            <lang locale="zh_TW" value="否" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumbeIsRepate].value">
            <lang locale="zh_CN" value="编码在系统中已存在，请重新输入！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="編碼在系統中已存在，請重新輸入！" />
            <lang locale="zh_TW" value="編碼在系統中已存在，請重新輸入！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumberIsOver80].value">
            <lang locale="zh_CN" value="编码不能超过80个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="編碼不能超過80個字元！" />
            <lang locale="zh_TW" value="編碼不能超過80個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[NumberNotNull].value">
            <lang locale="zh_CN" value="编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="編碼不能為空！" />
            <lang locale="zh_TW" value="編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OfferOutside].value">
            <lang locale="zh_CN" value="提出方不在系统范围内！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="提出方不在系統範圍內！" />
            <lang locale="zh_TW" value="提出方不在系統範圍內！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_ConstrParty].value">
            <lang locale="zh_CN" value="施工方" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="施工方" />
            <lang locale="zh_TW" value="施工方" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_DesignCom].value">
            <lang locale="zh_CN" value="设计公司" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="設計公司" />
            <lang locale="zh_TW" value="設計公司" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_SelfCom].value">
            <lang locale="zh_CN" value="我司" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="我司" />
            <lang locale="zh_TW" value="我司" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Offer_Superviser].value">
            <lang locale="zh_CN" value="监理方" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="監理方" />
            <lang locale="zh_TW" value="監理方" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberIsLong].value">
            <lang locale="zh_CN" value="组织编码长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼長度不能大於40！" />
            <lang locale="zh_TW" value="組織編碼長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberIsNull].value">
            <lang locale="zh_CN" value="组织编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼不能為空！" />
            <lang locale="zh_TW" value="組織編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberNonexist].value">
            <lang locale="zh_CN" value="组织编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織編碼在系統中不存在！" />
            <lang locale="zh_TW" value="組織編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OrgUnitNumberNotFound].value">
            <lang locale="zh_CN" value="组织长编码在工程项目所对应的成本中心不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="組織長編碼在工程項目所對應的成本中心不存在！" />
            <lang locale="zh_TW" value="組織長編碼在工程項目所對應的成本中心不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountIsOver40].value">
            <lang locale="zh_CN" value="奖励原币金额不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="獎勵原幣金額不能超過40個字元！" />
            <lang locale="zh_TW" value="獎勵原幣金額不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountNotNull].value">
            <lang locale="zh_CN" value="奖励原币金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="獎勵原幣金額不能為空！" />
            <lang locale="zh_TW" value="獎勵原幣金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[OriginalAmountNotNumber].value">
            <lang locale="zh_CN" value="奖励原币金额必须是数字！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="獎勵原幣金額必須是數字！" />
            <lang locale="zh_TW" value="獎勵原幣金額必須是數字！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PriceIsOverLenth].value">
            <lang locale="zh_CN" value="金额最大不能超过19位！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="金額最大不能超過19位！" />
            <lang locale="zh_TW" value="金額最大不能超過19位！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProductTypeNotFound].value">
            <lang locale="zh_CN" value="直接归属在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="直接歸屬在系統中不存在！" />
            <lang locale="zh_TW" value="直接歸屬在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberIsLong].value">
            <lang locale="zh_CN" value="工程项目编码长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼長度不能大於40！" />
            <lang locale="zh_TW" value="工程項目編碼長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberIsNull].value">
            <lang locale="zh_CN" value="工程项目编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼不能為空！" />
            <lang locale="zh_TW" value="工程項目編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ProjectNumberNonexist].value">
            <lang locale="zh_CN" value="工程项目编码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程項目編碼在系統中不存在！" />
            <lang locale="zh_TW" value="工程項目編碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeIsError].value">
            <lang locale="zh_CN" value="请按照提示信息正确填写发放方式！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請按照提示信息正確填寫發放方式！" />
            <lang locale="zh_TW" value="請按照提示信息正確填寫發放方式！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeIsOver40].value">
            <lang locale="zh_CN" value="发放方式不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="發放方式不能超過40個字元！" />
            <lang locale="zh_TW" value="發放方式不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[PutOutTypeNotNull].value">
            <lang locale="zh_CN" value="发放方式不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="發放方式不能為空！" />
            <lang locale="zh_TW" value="發放方式不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[ReaDescIsLong].value">
            <lang locale="zh_CN" value="原因说明长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="原因說明長度不能大於40！" />
            <lang locale="zh_TW" value="原因說明長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SpecialtyTypeIsNull].value">
            <lang locale="zh_CN" value="专业类型不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="專業類型不能為空！" />
            <lang locale="zh_TW" value="專業類型不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SpecialtyTypeNonexist].value">
            <lang locale="zh_CN" value="专业类型在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="專業類型在系統中不存在！" />
            <lang locale="zh_TW" value="專業類型在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[SplitScaleNotNull].value">
            <lang locale="zh_CN" value="拆分比例不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分比例不能為空！" />
            <lang locale="zh_TW" value="拆分比例不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[StateIsOver40].value">
            <lang locale="zh_CN" value="状态不能超过40个字符！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="狀態不能超過40個字元！" />
            <lang locale="zh_TW" value="狀態不能超過40個字元！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[State].value">
            <lang locale="zh_CN" value="请按照提示信息正确填写状态！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請按照提示信息正確填寫狀態！" />
            <lang locale="zh_TW" value="請按照提示信息正確填寫狀態！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Ticket].value">
            <lang locale="zh_CN" value="发票 我方转账" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="發票 我方轉賬" />
            <lang locale="zh_TW" value="發票 我方轉賬" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegreeIsNull].value">
            <lang locale="zh_CN" value="紧急程度不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="緊急程度不能為空！" />
            <lang locale="zh_TW" value="緊急程度不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegreeOutSide].value">
            <lang locale="zh_CN" value="紧急程度不在系统范围内！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="緊急程度不在系統範圍內！" />
            <lang locale="zh_TW" value="緊急程度不在系統範圍內！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegree_Normal].value">
            <lang locale="zh_CN" value="普通" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="普通" />
            <lang locale="zh_TW" value="普通" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UrgentDegree_Urgent].value">
            <lang locale="zh_CN" value="紧急" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="緊急" />
            <lang locale="zh_TW" value="緊急" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[UserNonexist].value">
            <lang locale="zh_CN" value="创建人/审核人在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="創建人/審核人在系統中不存在！" />
            <lang locale="zh_TW" value="創建人/審核人在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[Yes].value">
            <lang locale="zh_CN" value="是" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是" />
            <lang locale="zh_TW" value="是" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[curProjectInfo].value">
            <lang locale="zh_CN" value="归属财务核算对象代码在系统中不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="歸屬財務核算對象代碼在系統中不存在！" />
            <lang locale="zh_TW" value="歸屬財務核算對象代碼在系統中不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fBalanceTypeIsTooLong].value">
            <lang locale="zh_CN" value="结算方式字符长度不能大于40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="結算方式字元長度不能大於40！" />
            <lang locale="zh_TW" value="結算方式字元長度不能大於40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fConstructPriceIsOverLength].value">
            <lang locale="zh_CN" value="施工方报审金额最大不能超过19位！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="施工方報審金額最大不能超過19位！" />
            <lang locale="zh_TW" value="施工方報審金額最大不能超過19位！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fContentSeqIsNull].value">
            <lang locale="zh_CN" value="执行内容序列号不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="執行內容序列號不能為空！" />
            <lang locale="zh_TW" value="執行內容序列號不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCopySuppNameIsNotExsit].value">
            <lang locale="zh_CN" value="抄送单位不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="抄送單位不存在！" />
            <lang locale="zh_TW" value="抄送單位不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostAmountIsNull].value">
            <lang locale="zh_CN" value="测算金额不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="測算金額不能為空！" />
            <lang locale="zh_TW" value="測算金額不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostAmountIsOverLength].value">
            <lang locale="zh_CN" value="测算金额最大不能超过19位！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="測算金額最大不能超過19位！" />
            <lang locale="zh_TW" value="測算金額最大不能超過19位！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fCostDescriptionIsTooLong].value">
            <lang locale="zh_CN" value="测算说明字段长度不能超过40！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="測算說明字段長度不能超過40！" />
            <lang locale="zh_TW" value="測算說明字段長度不能超過40！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDeductAmountIsOverLength].value">
            <lang locale="zh_CN" value="责任扣款金额最大不能超过19位！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="責任扣款金額最大不能超過19位！" />
            <lang locale="zh_TW" value="責任扣款金額最大不能超過19位！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDutyOrgNameIsNotExsit].value">
            <lang locale="zh_CN" value="该责任归属部门不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該責任歸屬部門不存在！" />
            <lang locale="zh_TW" value="該責任歸屬部門不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fDutyOrgNameIsNull].value">
            <lang locale="zh_CN" value="责任归属部门不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="責任歸屬部門不能為空！" />
            <lang locale="zh_TW" value="責任歸屬部門不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[fReckonorNameIsNotExsit].value">
            <lang locale="zh_CN" value="该测算人名称不存在！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該測算人名稱不存在！" />
            <lang locale="zh_TW" value="該測算人名稱不存在！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.contract.ContractTransmissionResource].resourceItems.resourceItem[splitScaleError].value">
            <lang locale="zh_CN" value="拆分比例只能在在0-100之间！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="拆分比例只能在在0-100之間！" />
            <lang locale="zh_TW" value="拆分比例只能在在0-100之間！" />
        </rs>
    </resource>
</i18nResource>

