<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.fdc.webservice</package>
    <name>FDCWebSrvResource</name>
    <alias>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.fdc.webservice.FDCWebSrvResource</className>
    <resourceItems>
        <resourceItem>
            <name>0000</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0000].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>0001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>0002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>9999</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[9999].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1000</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1000].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1003</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1003].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1004</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1004].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1005</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1005].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1006</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1006].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1007</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1007].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1008</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1008].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1009</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1009].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1010</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1010].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1011</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1011].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1012</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1012].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1013</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1013].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>2001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>2002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>2003</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2003].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>2004</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2004].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>3001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>3002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>3003</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3003].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>3004</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3004].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>4001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[4001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>4002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[4002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7001</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7001].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7002</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7002].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7003</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7003].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7004</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7004].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7005</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7005].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7006</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7006].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7007</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7007].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7008</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7008].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7009</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7009].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7011</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7011].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7101</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7101].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7102</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7102].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7201</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7201].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7202</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7202].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7301</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7301].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7401</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7401].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7402</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7402].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7501</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7501].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7601</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7601].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7602</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7602].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7701</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7701].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7702</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7702].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7801</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7801].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7802</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7802].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7901</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7901].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>7902</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7902].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1014</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1014].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>1015</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1015].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>NO</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[NO].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>*IS_LO</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_LO].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>*IS_AM</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_AM].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>*IS_NU</name>
            <value>i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_NU].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].alias">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="房地产处理信息定义资源" />
            <lang locale="zh_TW" value="房地產處理信息定義資源" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].description">
            <lang locale="en_US" value="null" />
            <lang locale="zh_CN" value="null" />
            <lang locale="zh_TW" value="null" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_AM].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="不计成本的金额" />
            <lang locale="zh_TW" value="不計成本的金額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_LO].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="是否单独计算" />
            <lang locale="zh_TW" value="是否單獨計算" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[*IS_NU].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="对应主合同编码" />
            <lang locale="zh_TW" value="對應主合同編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0000].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="导入成功" />
            <lang locale="zh_TW" value="導入成功" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的组织编码找不到组织" />
            <lang locale="zh_TW" value="根據傳入的組織編碼找不到組織" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[0002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="暂时不支持" />
            <lang locale="zh_TW" value="暫時不支持" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1000].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="已经导入过" />
            <lang locale="zh_TW" value="已經導入過" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的合同类型编码找不到合同类型" />
            <lang locale="zh_TW" value="根據傳入的合同類型編碼找不到合同類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的工程项目编码找不到工程项目" />
            <lang locale="zh_TW" value="根據傳入的工程項目編碼找不到工程項目" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1003].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的币别找不到币别" />
            <lang locale="zh_TW" value="根據傳入的幣別找不到幣別" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1004].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的合同类型编码找不到合同类型" />
            <lang locale="zh_TW" value="根據傳入的合同類型編碼找不到合同類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1005].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的甲方编码找不到甲方" />
            <lang locale="zh_TW" value="根據傳入的甲方編碼找不到甲方" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1006].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的乙方编码找不到乙方" />
            <lang locale="zh_TW" value="根據傳入的乙方編碼找不到乙方" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1007].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的变更类型编码找不到变更类型" />
            <lang locale="zh_TW" value="根據傳入的變更類型編碼找不到變更類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1008].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的变更原因编码找不到变更原因" />
            <lang locale="zh_TW" value="根據傳入的變更原因編碼找不到變更原因" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1009].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="根据传入的承包类型编码没有找到承包类型" />
            <lang locale="zh_TW" value="根據傳入的承包類型編碼沒有找到承包類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1010].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有找到专业类型" />
            <lang locale="zh_TW" value="沒有找到專業類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1011].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有找到对应的合同" />
            <lang locale="zh_TW" value="沒有找到對應的合同" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1012].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有找到违约类型" />
            <lang locale="zh_TW" value="沒有找到違約類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1013].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有找到扣款单位" />
            <lang locale="zh_TW" value="沒有找到扣款單位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1014].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有找到对应的付款申请单" />
            <lang locale="zh_TW" value="沒有找到對應的付款申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[1015].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="付款申请单还没有审核" />
            <lang locale="zh_TW" value="付款申請單還沒有審核" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据编码不能为空" />
            <lang locale="zh_TW" value="單據編碼不能為空" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据名称不能为空" />
            <lang locale="zh_TW" value="單據名稱不能為空" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2003].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="签约日期不能为空" />
            <lang locale="zh_TW" value="簽約日期不能為空" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[2004].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="执行内容不能为空" />
            <lang locale="zh_TW" value="執行內容不能為空" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据状态不匹配" />
            <lang locale="zh_TW" value="單據狀態不匹配" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同性质不匹配" />
            <lang locale="zh_TW" value="合同性質不匹配" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3003].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="造价性质不匹配" />
            <lang locale="zh_TW" value="造價性質不匹配" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[3004].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="形成方式不匹配" />
            <lang locale="zh_TW" value="形成方式不匹配" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[4001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="金额为零" />
            <lang locale="zh_TW" value="金額為零" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[4002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="工程项目必须为明细分期" />
            <lang locale="zh_TW" value="工程項目必須為明細分期" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7001].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算，不能作废" />
            <lang locale="zh_TW" value="合同已經結算，不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7002].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经拆分，不能作废" />
            <lang locale="zh_TW" value="合同已經拆分，不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7003].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经修订，不能作废" />
            <lang locale="zh_TW" value="合同已經修訂，不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7004].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被变更审批单引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被變更審批單引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7005].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被变更指令单引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被變更指令單引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7006].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被违约金引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被違約金引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7007].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被奖励金引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被獎勵金引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7008].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被扣款单引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被扣款單引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7009].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经被付款申请引用,不能作废" />
            <lang locale="zh_TW" value="合同已經被付款申請引用,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7011].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="value_new" />
            <lang locale="zh_TW" value="value_new" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7101].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算,变更审批单不能作废" />
            <lang locale="zh_TW" value="合同已經結算,變更審批單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7102].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="已经被变更指令单引用,变更审批单不能作废" />
            <lang locale="zh_TW" value="已經被變更指令單引用,變更審批單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7201].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算，变更指令单不能作废" />
            <lang locale="zh_TW" value="合同已經結算，變更指令單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7202].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="变更已经拆分" />
            <lang locale="zh_TW" value="變更已經拆分" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7301].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="value_new" />
            <lang locale="zh_TW" value="value_new" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7401].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="结算已经拆分,不能作废" />
            <lang locale="zh_TW" value="結算已經拆分,不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7402].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="已经存在结算款付款申请单" />
            <lang locale="zh_TW" value="已經存在結算款付款申請單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7501].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="无文本合同已经生成付款单，不能作废" />
            <lang locale="zh_TW" value="無文本合同已經生成付款單，不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7601].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算，违约单不能作废" />
            <lang locale="zh_TW" value="合同已經結算，違約單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7602].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据已经被付款申请单引用" />
            <lang locale="zh_TW" value="單據已經被付款申請單引用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7701].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算，奖励单不能作废" />
            <lang locale="zh_TW" value="合同已經結算，獎勵單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7702].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据已经被付款申请单引用" />
            <lang locale="zh_TW" value="單據已經被付款申請單引用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7801].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="合同已经结算，扣款单不能作废" />
            <lang locale="zh_TW" value="合同已經結算，扣款單不能作廢" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7802].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="单据已经被付款申请单引用" />
            <lang locale="zh_TW" value="單據已經被付款申請單引用" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7901].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="付款申请单已经生成对应的付款单" />
            <lang locale="zh_TW" value="付款申請單已經生成對應的付款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[7902].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="付款单已经拆分不能作废付款单" />
            <lang locale="zh_TW" value="付款單已經拆分不能作廢付款單" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[9999].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="没有单据传入" />
            <lang locale="zh_TW" value="沒有單據傳入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.webservice.FDCWebSrvResource].resourceItems.resourceItem[NO].value">
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_CN" value="否" />
            <lang locale="zh_TW" value="否" />
        </rs>
    </resource>
</i18nResource>

