<?xml version="1.0" encoding="UTF-8"?>
<i18nResource xmlns="com.kingdee.bos.metadata">
    <package>com.kingdee.eas.fdc.invite.supplier</package>
    <name>SupplierResource</name>
    <alias>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].alias</alias>
    <description>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].description</description>
    <userDefined>false</userDefined>
    <className>com.kingdee.eas.fdc.invite.supplier.SupplierResource</className>
    <resourceItems>
        <resourceItem>
            <name>auditScore</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditScore].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>template</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[template].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierType</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bizDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bizDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>address</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[address].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>person</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[person].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isReview</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isReview].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierGrade</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierGrade].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>add</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[add].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>delete</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[delete].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>from</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[from].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>update</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[update].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>kind</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[kind].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>deputy</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deputy].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bornDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bornDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>money</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[money].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>currency</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[currency].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>homepage</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[homepage].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>license</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[license].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>handTotal</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[handTotal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>workersAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workersAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>researchAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[researchAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>managerAmount</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[managerAmount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>province</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[province].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>city</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[city].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>postalcode</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[postalcode].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>companyPhone</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyPhone].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>companyMailbox</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyMailbox].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fax</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fax].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>companyAddress</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyAddress].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>asset</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[asset].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>indebted</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indebted].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bank</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bank].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>account</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[account].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bankGrade</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bankGrade].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bankLinkman</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bankLinkman].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>area</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[area].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>contract</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[contract].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>evaluateDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluateDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isEvaluate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isEvaluate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>areaNumberNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNumberNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>areaNameNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNameNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>especially</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[especially].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>areaNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>again</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[again].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>areaName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notEdit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notEdit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notRemove</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notRemove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notUnAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notUnAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>renovate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[renovate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>renovateSucceed</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[renovateSucceed].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>appointSupplierType</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[appointSupplierType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>accessory</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[accessory].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>pointRow</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[pointRow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>afterAccessory</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[afterAccessory].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notSubmit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSubmit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierTypeNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierTypeNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>companyName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>number</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[number].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>bornDateNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bornDateNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>licenseNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[licenseNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>provinceNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[provinceNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>phoneNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[phoneNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mailNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[mailNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>faxNotNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[faxNotNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fileNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fileNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>fileName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fileName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>projectName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[projectName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>clientName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>contractTotal</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[contractTotal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>compare</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[compare].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierAnd</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierAnd].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>deputySame</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deputySame].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>level</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[level].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>name</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[name].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>dimensionality</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[dimensionality].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>leafage</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[leafage].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>haveNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[haveNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>syndicDimensiona</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndicDimensiona].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>indexNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indexNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>indexName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indexName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>serviceType</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[serviceType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>basicClass</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[basicClass].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>superior</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[superior].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAuditTemplate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unAuditTemplate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>addNew</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[addNew].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditState</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditState].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>distract</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[distract].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>insert</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[insert].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sum</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sum].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>next</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[next].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>rowAdd</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[rowAdd].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notSameIndex</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSameIndex].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>weight</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[weight].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>lessZero</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[lessZero].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>moreHundred</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[moreHundred].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>modelNumber</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[modelNumber].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>syndicPhase</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndicPhase].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>model</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[model].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>deleteS</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteS].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>AreaDelete</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[AreaDelete].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>changing</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[changing].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>auditedNotEdit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditedNotEdit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>onTotal</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[onTotal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>againInput</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[againInput].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>index</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[index].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>choiceOne</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[choiceOne].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>haved</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[haved].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>doNot</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[doNot].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notOne</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notOne].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>type</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[type].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notState</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notState].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notEnter</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notEnter].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>unAudit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unAudit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isForbid</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isForbid].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>reveal</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[reveal].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>phone</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[phone].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supType</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supType].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isChange</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isChange].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>mailBox</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[mailBox].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>linkPerson</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[linkPerson].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sale</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sale].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>threeYear</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[threeYear].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>aptitude</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[aptitude].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>endTime</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[endTime].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>aptitudeFile</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[aptitudeFile].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>clientAddress</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientAddress].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>clientLink</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientLink].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>startDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[startDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>endDate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[endDate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>personCount</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[personCount].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>achievement</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[achievement].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>changeTemplet</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[changeTemplet].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>templateNull</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[templateNull].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>year</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[year].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplier</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplier].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierUtil</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierUtil].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isProhibit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isProhibit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>workPhone</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workPhone].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>remark</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[remark].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>isRemove</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isRemove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>duty</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[duty].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>telephone</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[telephone].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>workClass</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workClass].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>serviceArea</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[serviceArea].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>review</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[review].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>evaluate</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluate].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>syndic</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndic].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>repeat</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[repeat].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notAddBase</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notAddBase].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>zhongBiao</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[zhongBiao].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notZhongBiao</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notZhongBiao].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>excerpted</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[excerpted].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>junior</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[junior].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>gradeName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[gradeName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>evaluateModel</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluateModel].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>linkFax</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[linkFax].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>attachment</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[attachment].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>selectBaseClass</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[selectBaseClass].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notSave</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSave].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>firmName</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[firmName].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>being</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[being].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>insertRow</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[insertRow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>deleteRow</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteRow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>notSame</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSame].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>nameB</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[nameB].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>baseInfo</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[baseInfo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>addRow</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[addRow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierInfoDeleted</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierInfoDeleted].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>supplierInfoWorkFlow</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierInfoWorkFlow].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>deleteInfo</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteInfo].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>reviewPass</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[reviewPass].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>sure</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sure].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>approve</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[approve].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>canntedit</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntedit].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>canntremove</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntremove].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>canntview</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntview].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>orgEnterHis</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgEnterHis].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>orgEnterHis2</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgEnterHis2].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>orgAppHis</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgAppHis].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
        <resourceItem>
            <name>orgConHis</name>
            <value>i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgConHis].value</value>
            <userDefined>false</userDefined>
        </resourceItem>
    </resourceItems>
    <resource>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].alias">
            <lang locale="zh_CN" value="供应商资源文件" />
            <lang locale="en_US" value="null" />
            <lang locale="zh_HK" value="供應商資源文件" />
            <lang locale="zh_TW" value="供應商資源文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].description">
            <lang locale="zh_CN" value="供应商资源文件" />
            <lang locale="en_US" value="null" />
            <lang locale="zh_HK" value="供應商資源文件" />
            <lang locale="zh_TW" value="供應商資源文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[AreaDelete].value">
            <lang locale="zh_CN" value="此区域名称已被引用，不能进行删除操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="此區域名稱已被引用，不能進行刪除操作！" />
            <lang locale="zh_TW" value="此區域名稱已被引用，不能進行刪除操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[accessory].value">
            <lang locale="zh_CN" value="请先保存,再上传附件！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請先保存,再上傳附件！" />
            <lang locale="zh_TW" value="請先保存,再上傳附件！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[account].value">
            <lang locale="zh_CN" value="银行帐户" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="銀行帳戶" />
            <lang locale="zh_TW" value="銀行帳戶" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[achievement].value">
            <lang locale="zh_CN" value="业绩" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="業績" />
            <lang locale="zh_TW" value="業績" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[addNew].value">
            <lang locale="zh_CN" value="新增" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="新增" />
            <lang locale="zh_TW" value="新增" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[addRow].value">
            <lang locale="zh_CN" value="新增行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="新增行" />
            <lang locale="zh_TW" value="新增行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[add].value">
            <lang locale="zh_CN" value="增加" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="增加" />
            <lang locale="zh_TW" value="增加" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[address].value">
            <lang locale="zh_CN" value="考察地点不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="考察地點不能為空！" />
            <lang locale="zh_TW" value="考察地點不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[afterAccessory].value">
            <lang locale="zh_CN" value="请先保存分录,再上传附件！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請先保存分錄,再上傳附件！" />
            <lang locale="zh_TW" value="請先保存分錄,再上傳附件！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[againInput].value">
            <lang locale="zh_CN" value="已经存在，请重新输入！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已經存在，請重新輸入！" />
            <lang locale="zh_TW" value="已經存在，請重新輸入！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[again].value">
            <lang locale="zh_CN" value="已经存在，请重新输入！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已經存在，請重新輸入！" />
            <lang locale="zh_TW" value="已經存在，請重新輸入！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[appointSupplierType].value">
            <lang locale="zh_CN" value="请选中要导入的供应商类型！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選中要導入的供應商類型！" />
            <lang locale="zh_TW" value="請選中要導入的供應商類型！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[approve].value">
            <lang locale="zh_CN" value="核准" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="核准" />
            <lang locale="zh_TW" value="核准" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[aptitudeFile].value">
            <lang locale="zh_CN" value="资质文件" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="資質文件" />
            <lang locale="zh_TW" value="資質文件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[aptitude].value">
            <lang locale="zh_CN" value="资质等级" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="資質等級" />
            <lang locale="zh_TW" value="資質等級" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNameNotNull].value">
            <lang locale="zh_CN" value="区域名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="區域名稱不能為空！" />
            <lang locale="zh_TW" value="區域名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaName].value">
            <lang locale="zh_CN" value="区域名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="區域名稱" />
            <lang locale="zh_TW" value="區域名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNumberNotNull].value">
            <lang locale="zh_CN" value="区域编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="區域編碼不能為空！" />
            <lang locale="zh_TW" value="區域編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[areaNumber].value">
            <lang locale="zh_CN" value="区域编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="區域編碼" />
            <lang locale="zh_TW" value="區域編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[area].value">
            <lang locale="zh_CN" value="经营范围" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="經營範圍" />
            <lang locale="zh_TW" value="經營範圍" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[asset].value">
            <lang locale="zh_CN" value="净资产" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="淨資產" />
            <lang locale="zh_TW" value="淨資產" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[attachment].value">
            <lang locale="zh_CN" value="附件" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="附件" />
            <lang locale="zh_TW" value="附件" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditScore].value">
            <lang locale="zh_CN" value="评审得分不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審得分不能為空！" />
            <lang locale="zh_TW" value="評審得分不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditState].value">
            <lang locale="zh_CN" value="已审批状态不能删除！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已審批狀態不能刪除！" />
            <lang locale="zh_TW" value="已審批狀態不能刪除！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[auditedNotEdit].value">
            <lang locale="zh_CN" value="已审批的数据不能修改！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="已審批的數據不能修改！" />
            <lang locale="zh_TW" value="已審批的數據不能修改！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bankGrade].value">
            <lang locale="zh_CN" value="银行信用等级" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="銀行信用等級" />
            <lang locale="zh_TW" value="銀行信用等級" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bankLinkman].value">
            <lang locale="zh_CN" value="银行联系人" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="銀行聯繫人" />
            <lang locale="zh_TW" value="銀行聯繫人" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bank].value">
            <lang locale="zh_CN" value="开户银行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="開戶銀行" />
            <lang locale="zh_TW" value="開戶銀行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[baseInfo].value">
            <lang locale="zh_CN" value="基本信息" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="基本信息" />
            <lang locale="zh_TW" value="基本信息" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[basicClass].value">
            <lang locale="zh_CN" value="基本分类" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="基本分類" />
            <lang locale="zh_TW" value="基本分類" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[being].value">
            <lang locale="zh_CN" value="存在" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="存在" />
            <lang locale="zh_TW" value="存在" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bizDate].value">
            <lang locale="zh_CN" value="考察日期不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="考察日期不能為空！" />
            <lang locale="zh_TW" value="考察日期不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bornDateNotNull].value">
            <lang locale="zh_CN" value="成立日期不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="成立日期不能為空！" />
            <lang locale="zh_TW" value="成立日期不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[bornDate].value">
            <lang locale="zh_CN" value="成立日期" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="成立日期" />
            <lang locale="zh_TW" value="成立日期" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntedit].value">
            <lang locale="zh_CN" value="在当前组织下,不能修改该基础资料!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在當前組織下,不能修改該基礎資料!" />
            <lang locale="zh_TW" value="在當前組織下,不能修改該基礎資料!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntremove].value">
            <lang locale="zh_CN" value="在当前组织下,不能删除该基础资料!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在當前組織下,不能刪除該基礎資料!" />
            <lang locale="zh_TW" value="在當前組織下,不能刪除該基礎資料!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[canntview].value">
            <lang locale="zh_CN" value="在当前组织下,不能查看该基础资料!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="在當前組織下,不能查看該基礎資料!" />
            <lang locale="zh_TW" value="在當前組織下,不能查看該基礎資料!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[changeTemplet].value">
            <lang locale="zh_CN" value="该状态不能更换模板！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該狀態不能更換範本！" />
            <lang locale="zh_TW" value="該狀態不能更換範本！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[changing].value">
            <lang locale="zh_CN" value="该供应商正在进行信息变更！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該供應商正在進行信息變更！" />
            <lang locale="zh_TW" value="該供應商正在進行信息變更！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[choiceOne].value">
            <lang locale="zh_CN" value="请选择明细节点新增数据！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇明細節點新增數據！" />
            <lang locale="zh_TW" value="請選擇明細節點新增數據！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[city].value">
            <lang locale="zh_CN" value="所在城市" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="所在城市" />
            <lang locale="zh_TW" value="所在城市" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientAddress].value">
            <lang locale="zh_CN" value="客户地址" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="客戶地址" />
            <lang locale="zh_TW" value="客戶地址" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientLink].value">
            <lang locale="zh_CN" value="客户联系人" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="客戶聯繫人" />
            <lang locale="zh_TW" value="客戶聯繫人" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[clientName].value">
            <lang locale="zh_CN" value="客户名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="客戶名稱" />
            <lang locale="zh_TW" value="客戶名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyAddress].value">
            <lang locale="zh_CN" value="公司地址" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司地址" />
            <lang locale="zh_TW" value="公司地址" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyMailbox].value">
            <lang locale="zh_CN" value="公司邮箱" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司郵箱" />
            <lang locale="zh_TW" value="公司郵箱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyName].value">
            <lang locale="zh_CN" value="公司名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司名稱不能為空！" />
            <lang locale="zh_TW" value="公司名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[companyPhone].value">
            <lang locale="zh_CN" value="公司电话" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司電話" />
            <lang locale="zh_TW" value="公司電話" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[compare].value">
            <lang locale="zh_CN" value="截止日期不能早于开始日期！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="截止日期不能早於開始日期！" />
            <lang locale="zh_TW" value="截止日期不能早於開始日期！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[contractTotal].value">
            <lang locale="zh_CN" value="合同总额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同總額" />
            <lang locale="zh_TW" value="合同總額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[contract].value">
            <lang locale="zh_CN" value="合同名称不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合同名稱不能為空！" />
            <lang locale="zh_TW" value="合同名稱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[currency].value">
            <lang locale="zh_CN" value="币别" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="幣別" />
            <lang locale="zh_TW" value="幣別" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteInfo].value">
            <lang locale="zh_CN" value="该供应商正在做信息变更，是否确认删除当前信息变更？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該供應商正在做信息變更，是否確認刪除當前信息變更？" />
            <lang locale="zh_TW" value="該供應商正在做信息變更，是否確認刪除當前信息變更？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteRow].value">
            <lang locale="zh_CN" value="删除行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="刪除行" />
            <lang locale="zh_TW" value="刪除行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deleteS].value">
            <lang locale="zh_CN" value="是否确认删除？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否確認刪除？" />
            <lang locale="zh_TW" value="是否確認刪除？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[delete].value">
            <lang locale="zh_CN" value="删除" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="刪除" />
            <lang locale="zh_TW" value="刪除" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deputySame].value">
            <lang locale="zh_CN" value="法人相同的名称,是否确认？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="法人相同的名稱,是否確認？" />
            <lang locale="zh_TW" value="法人相同的名稱,是否確認？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[deputy].value">
            <lang locale="zh_CN" value="法人代表" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="法人代表" />
            <lang locale="zh_TW" value="法人代表" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[dimensionality].value">
            <lang locale="zh_CN" value="维度" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="維度" />
            <lang locale="zh_TW" value="維度" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[distract].value">
            <lang locale="zh_CN" value="分录" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="分錄" />
            <lang locale="zh_TW" value="分錄" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[doNot].value">
            <lang locale="zh_CN" value="，不能进行此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="，不能進行此操作！" />
            <lang locale="zh_TW" value="，不能進行此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[duty].value">
            <lang locale="zh_CN" value="职务" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="職務" />
            <lang locale="zh_TW" value="職務" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[endDate].value">
            <lang locale="zh_CN" value="截止日期" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="截止日期" />
            <lang locale="zh_TW" value="截止日期" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[endTime].value">
            <lang locale="zh_CN" value="到期时间" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="到期時間" />
            <lang locale="zh_TW" value="到期時間" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[especially].value">
            <lang locale="zh_CN" value="区域名称太长或含有特殊符号！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="區域名稱太長或含有特殊符號！" />
            <lang locale="zh_TW" value="區域名稱太長或含有特殊符號！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluateDate].value">
            <lang locale="zh_CN" value="评估时间不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評估時間不能為空！" />
            <lang locale="zh_TW" value="評估時間不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluateModel].value">
            <lang locale="zh_CN" value="评审模板" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審範本" />
            <lang locale="zh_TW" value="評審範本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[evaluate].value">
            <lang locale="zh_CN" value="履约评估" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="履約評估" />
            <lang locale="zh_TW" value="履約評估" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[excerpted].value">
            <lang locale="zh_CN" value="该记录已经被引用，不能执行此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該記錄已經被引用，不能執行此操作！" />
            <lang locale="zh_TW" value="該記錄已經被引用，不能執行此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[faxNotNull].value">
            <lang locale="zh_CN" value="公司传真不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司傳真不能為空！" />
            <lang locale="zh_TW" value="公司傳真不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fax].value">
            <lang locale="zh_CN" value="传真" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="傳真" />
            <lang locale="zh_TW" value="傳真" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fileName].value">
            <lang locale="zh_CN" value="文件名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="文件名稱" />
            <lang locale="zh_TW" value="文件名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[fileNumber].value">
            <lang locale="zh_CN" value="文件标号" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="文件標號" />
            <lang locale="zh_TW" value="文件標號" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[firmName].value">
            <lang locale="zh_CN" value="公司名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司名稱" />
            <lang locale="zh_TW" value="公司名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[from].value">
            <lang locale="zh_CN" value="从" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="從" />
            <lang locale="zh_TW" value="從" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[gradeName].value">
            <lang locale="zh_CN" value="等级别名" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="等級別名" />
            <lang locale="zh_TW" value="等級別名" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[handTotal].value">
            <lang locale="zh_CN" value="雇员总数" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="雇員總數" />
            <lang locale="zh_TW" value="雇員總數" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[haveNumber].value">
            <lang locale="zh_CN" value="评审维度已经有数据，不能进行此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審維度已經有數據，不能進行此操作！" />
            <lang locale="zh_TW" value="評審維度已經有數據，不能進行此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[haved].value">
            <lang locale="zh_CN" value="明细类别已经有数据" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="明細類別已經有數據" />
            <lang locale="zh_TW" value="明細類別已經有數據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[homepage].value">
            <lang locale="zh_CN" value="公司主页" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司主頁" />
            <lang locale="zh_TW" value="公司主頁" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indebted].value">
            <lang locale="zh_CN" value="资产负债率" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="資產負債率" />
            <lang locale="zh_TW" value="資產負債率" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indexName].value">
            <lang locale="zh_CN" value="评审指标名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審指標名稱" />
            <lang locale="zh_TW" value="評審指標名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[indexNumber].value">
            <lang locale="zh_CN" value="评审指标编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審指標編碼" />
            <lang locale="zh_TW" value="評審指標編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[index].value">
            <lang locale="zh_CN" value="评审指标" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審指標" />
            <lang locale="zh_TW" value="評審指標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[insertRow].value">
            <lang locale="zh_CN" value="插入行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="插入行" />
            <lang locale="zh_TW" value="插入行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[insert].value">
            <lang locale="zh_CN" value="插入" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="插入" />
            <lang locale="zh_TW" value="插入" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isAudit].value">
            <lang locale="zh_CN" value="确定不参与评审？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確定不參與評審？" />
            <lang locale="zh_TW" value="確定不參與評審？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isChange].value">
            <lang locale="zh_CN" value="是否将默认联系人改变为" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否將默認聯繫人改變為" />
            <lang locale="zh_TW" value="是否將默認聯繫人改變為" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isEvaluate].value">
            <lang locale="zh_CN" value="确定不参与评估？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確定不參與評估？" />
            <lang locale="zh_TW" value="確定不參與評估？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isForbid].value">
            <lang locale="zh_CN" value="是否确认禁用模版？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否確認禁用模版？" />
            <lang locale="zh_TW" value="是否確認禁用模版？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isProhibit].value">
            <lang locale="zh_CN" value="是否确定禁用该数据？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否確定禁用該數據？" />
            <lang locale="zh_TW" value="是否確定禁用該數據？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isRemove].value">
            <lang locale="zh_CN" value="是否确认删除当前单据？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="是否確認刪除當前單據？" />
            <lang locale="zh_TW" value="是否確認刪除當前單據？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[isReview].value">
            <lang locale="zh_CN" value="确定不参与考察？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="確定不參與考察？" />
            <lang locale="zh_TW" value="確定不參與考察？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[junior].value">
            <lang locale="zh_CN" value="下级已有数据，不能进行此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="下級已有數據，不能進行此操作！" />
            <lang locale="zh_TW" value="下級已有數據，不能進行此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[kind].value">
            <lang locale="zh_CN" value="企业性质" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="企業性質" />
            <lang locale="zh_TW" value="企業性質" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[leafage].value">
            <lang locale="zh_CN" value="非叶子节点，不能执行此操作！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="非葉子節點，不能執行此操作！" />
            <lang locale="zh_TW" value="非葉子節點，不能執行此操作！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[lessZero].value">
            <lang locale="zh_CN" value="不能小于0！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="不能小於0！" />
            <lang locale="zh_TW" value="不能小於0！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[level].value">
            <lang locale="zh_CN" value="本级编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="本級編碼" />
            <lang locale="zh_TW" value="本級編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[licenseNotNull].value">
            <lang locale="zh_CN" value="营业执照不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="營業執照不能為空！" />
            <lang locale="zh_TW" value="營業執照不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[license].value">
            <lang locale="zh_CN" value="营业执照" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="營業執照" />
            <lang locale="zh_TW" value="營業執照" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[linkFax].value">
            <lang locale="zh_CN" value="公司传真" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司傳真" />
            <lang locale="zh_TW" value="公司傳真" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[linkPerson].value">
            <lang locale="zh_CN" value="联系人" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="聯繫人" />
            <lang locale="zh_TW" value="聯繫人" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[mailBox].value">
            <lang locale="zh_CN" value="邮箱" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="郵箱" />
            <lang locale="zh_TW" value="郵箱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[mailNotNull].value">
            <lang locale="zh_CN" value="公司邮箱不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司郵箱不能為空！" />
            <lang locale="zh_TW" value="公司郵箱不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[managerAmount].value">
            <lang locale="zh_CN" value="管理人员数量" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="管理人員數量" />
            <lang locale="zh_TW" value="管理人員數量" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[modelNumber].value">
            <lang locale="zh_CN" value="模板编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="範本編碼" />
            <lang locale="zh_TW" value="範本編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[model].value">
            <lang locale="zh_CN" value="模板" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="範本" />
            <lang locale="zh_TW" value="範本" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[money].value">
            <lang locale="zh_CN" value="注册资金（万元）" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="註冊資金（萬元）" />
            <lang locale="zh_TW" value="註冊資金（萬元）" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[moreHundred].value">
            <lang locale="zh_CN" value="不能大于100！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="不能大於100！" />
            <lang locale="zh_TW" value="不能大於100！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[nameB].value">
            <lang locale="zh_CN" value="姓名" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="姓名" />
            <lang locale="zh_TW" value="姓名" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[name].value">
            <lang locale="zh_CN" value="名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="名稱" />
            <lang locale="zh_TW" value="名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[next].value">
            <lang locale="zh_CN" value="第" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="第" />
            <lang locale="zh_TW" value="第" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notAddBase].value">
            <lang locale="zh_CN" value="当前组织下,不能增加该类基础资料！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前組織下,不能增加該類基礎資料！" />
            <lang locale="zh_TW" value="當前組織下,不能增加該類基礎資料！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notAudit].value">
            <lang locale="zh_CN" value="当前状态不能进行核准！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能進行核准！" />
            <lang locale="zh_TW" value="當前狀態不能進行核准！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notEdit].value">
            <lang locale="zh_CN" value="当前状态不能修改！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能修改！" />
            <lang locale="zh_TW" value="當前狀態不能修改！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notEnter].value">
            <lang locale="zh_CN" value="非登录组织单据" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="非登錄組織單據" />
            <lang locale="zh_TW" value="非登錄組織單據" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notNull].value">
            <lang locale="zh_CN" value="不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="不能為空！" />
            <lang locale="zh_TW" value="不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notOne].value">
            <lang locale="zh_CN" value="非明细节点" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="非明細節點" />
            <lang locale="zh_TW" value="非明細節點" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notRemove].value">
            <lang locale="zh_CN" value="当前状态不能被删除！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能被刪除！" />
            <lang locale="zh_TW" value="當前狀態不能被刪除！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSameIndex].value">
            <lang locale="zh_CN" value="行不能为同一个评审指标！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="行不能為同一個評審指標！" />
            <lang locale="zh_TW" value="行不能為同一個評審指標！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSame].value">
            <lang locale="zh_CN" value="不能重复！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="不能重複！" />
            <lang locale="zh_TW" value="不能重複！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSave].value">
            <lang locale="zh_CN" value="当前状态不能保存！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能保存！" />
            <lang locale="zh_TW" value="當前狀態不能保存！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notState].value">
            <lang locale="zh_CN" value="当前单据状态不能审批！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前單據狀態不能審批！" />
            <lang locale="zh_TW" value="當前單據狀態不能審批！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notSubmit].value">
            <lang locale="zh_CN" value="当前状态不能提交！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能提交！" />
            <lang locale="zh_TW" value="當前狀態不能提交！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notUnAudit].value">
            <lang locale="zh_CN" value="当前状态不能进行反核准！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="當前狀態不能進行反核准！" />
            <lang locale="zh_TW" value="當前狀態不能進行反核准！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[notZhongBiao].value">
            <lang locale="zh_CN" value="未中标" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="未中標" />
            <lang locale="zh_TW" value="未中標" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[number].value">
            <lang locale="zh_CN" value="编码不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="編碼不能為空！" />
            <lang locale="zh_TW" value="編碼不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[onTotal].value">
            <lang locale="zh_CN" value="之和" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="之和" />
            <lang locale="zh_TW" value="之和" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgAppHis].value">
            <lang locale="zh_CN" value="的 供应商库_评审历史 业务权限!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="的 供應商庫_評審歷史 業務許可權!" />
            <lang locale="zh_TW" value="的 供應商庫_評審歷史 業務許可權!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgConHis].value">
            <lang locale="zh_CN" value="的 供应商库_签约历史 业务权限!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="的 供應商庫_簽約歷史 業務許可權!" />
            <lang locale="zh_TW" value="的 供應商庫_簽約歷史 業務許可權!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgEnterHis2].value">
            <lang locale="zh_CN" value="的 供应商库_入围历史 业务权限!" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="的 供應商庫_入圍歷史 業務許可權!" />
            <lang locale="zh_TW" value="的 供應商庫_入圍歷史 業務許可權!" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[orgEnterHis].value">
            <lang locale="zh_CN" value="你没有组织:" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="你沒有組織:" />
            <lang locale="zh_TW" value="你沒有組織:" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[personCount].value">
            <lang locale="zh_CN" value="投入人数" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="投入人數" />
            <lang locale="zh_TW" value="投入人數" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[person].value">
            <lang locale="zh_CN" value="参与人员不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="參與人員不能為空！" />
            <lang locale="zh_TW" value="參與人員不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[phoneNotNull].value">
            <lang locale="zh_CN" value="公司电话不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="公司電話不能為空！" />
            <lang locale="zh_TW" value="公司電話不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[phone].value">
            <lang locale="zh_CN" value="电话" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="電話" />
            <lang locale="zh_TW" value="電話" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[pointRow].value">
            <lang locale="zh_CN" value="请选择行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇行" />
            <lang locale="zh_TW" value="請選擇行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[postalcode].value">
            <lang locale="zh_CN" value="邮编" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="郵編" />
            <lang locale="zh_TW" value="郵編" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[projectName].value">
            <lang locale="zh_CN" value="工程名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="工程名稱" />
            <lang locale="zh_TW" value="工程名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[provinceNotNull].value">
            <lang locale="zh_CN" value="所在省份不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="所在省份不能為空！" />
            <lang locale="zh_TW" value="所在省份不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[province].value">
            <lang locale="zh_CN" value="所在省份" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="所在省份" />
            <lang locale="zh_TW" value="所在省份" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[remark].value">
            <lang locale="zh_CN" value="备注" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="備註" />
            <lang locale="zh_TW" value="備註" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[renovateSucceed].value">
            <lang locale="zh_CN" value="导入成功" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="導入成功" />
            <lang locale="zh_TW" value="導入成功" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[renovate].value">
            <lang locale="zh_CN" value="无数据更新" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="無數據更新" />
            <lang locale="zh_TW" value="無數據更新" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[repeat].value">
            <lang locale="zh_CN" value="重复" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="重複" />
            <lang locale="zh_TW" value="重複" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[researchAmount].value">
            <lang locale="zh_CN" value="研发人员数量" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="研發人員數量" />
            <lang locale="zh_TW" value="研發人員數量" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[reveal].value">
            <lang locale="zh_CN" value="启用状态不能反审批！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="啟用狀態不能反審批！" />
            <lang locale="zh_TW" value="啟用狀態不能反審批！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[reviewPass].value">
            <lang locale="zh_CN" value="只有资格考察合格的才能进行" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="只有資格考察合格的才能進行" />
            <lang locale="zh_TW" value="只有資格考察合格的才能進行" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[review].value">
            <lang locale="zh_CN" value="资格考察" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="資格考察" />
            <lang locale="zh_TW" value="資格考察" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[rowAdd].value">
            <lang locale="zh_CN" value="行和" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="行和" />
            <lang locale="zh_TW" value="行和" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sale].value">
            <lang locale="zh_CN" value="销售额" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="銷售額" />
            <lang locale="zh_TW" value="銷售額" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[selectBaseClass].value">
            <lang locale="zh_CN" value="请选择具体的基本分类！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="請選擇具體的基本分類！" />
            <lang locale="zh_TW" value="請選擇具體的基本分類！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[serviceArea].value">
            <lang locale="zh_CN" value="服务区域" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="服務區域" />
            <lang locale="zh_TW" value="服務區域" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[serviceType].value">
            <lang locale="zh_CN" value="服务类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="服務類型" />
            <lang locale="zh_TW" value="服務類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[startDate].value">
            <lang locale="zh_CN" value="开始日期" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="開始日期" />
            <lang locale="zh_TW" value="開始日期" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sum].value">
            <lang locale="zh_CN" value="合计" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="合計" />
            <lang locale="zh_TW" value="合計" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supType].value">
            <lang locale="zh_CN" value="供应商类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商類型" />
            <lang locale="zh_TW" value="供應商類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[superior].value">
            <lang locale="zh_CN" value="上级编码" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="上級編碼" />
            <lang locale="zh_TW" value="上級編碼" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierAnd].value">
            <lang locale="zh_CN" value="供应商与" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商與" />
            <lang locale="zh_TW" value="供應商與" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierGrade].value">
            <lang locale="zh_CN" value="供应商等级不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商等級不能為空！" />
            <lang locale="zh_TW" value="供應商等級不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierInfoDeleted].value">
            <lang locale="zh_CN" value="该条供应商信息变更记录已经被删除！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該條供應商信息變更記錄已經被刪除！" />
            <lang locale="zh_TW" value="該條供應商信息變更記錄已經被刪除！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierInfoWorkFlow].value">
            <lang locale="zh_CN" value="该供应商正在做信息变更并且已在工作流中！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該供應商正在做信息變更並且已在工作流中！" />
            <lang locale="zh_TW" value="該供應商正在做信息變更並且已在工作流中！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierName].value">
            <lang locale="zh_CN" value="供应商名称" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商名稱" />
            <lang locale="zh_TW" value="供應商名稱" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierNumber].value">
            <lang locale="zh_CN" value="供应商编号" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商編號" />
            <lang locale="zh_TW" value="供應商編號" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierTypeNotNull].value">
            <lang locale="zh_CN" value="供应商类型不能为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商類型不能為空！" />
            <lang locale="zh_TW" value="供應商類型不能為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierType].value">
            <lang locale="zh_CN" value="服务类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="服務類型" />
            <lang locale="zh_TW" value="服務類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplierUtil].value">
            <lang locale="zh_CN" value="供方" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供方" />
            <lang locale="zh_TW" value="供方" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[supplier].value">
            <lang locale="zh_CN" value="供应商" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="供應商" />
            <lang locale="zh_TW" value="供應商" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[sure].value">
            <lang locale="zh_CN" value="！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="！" />
            <lang locale="zh_TW" value="！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndicDimensiona].value">
            <lang locale="zh_CN" value="评审维度" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審維度" />
            <lang locale="zh_TW" value="評審維度" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndicPhase].value">
            <lang locale="zh_CN" value="评审阶段" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="評審階段" />
            <lang locale="zh_TW" value="評審階段" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[syndic].value">
            <lang locale="zh_CN" value="定期评审" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="定期評審" />
            <lang locale="zh_TW" value="定期評審" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[telephone].value">
            <lang locale="zh_CN" value="手机" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="手機" />
            <lang locale="zh_TW" value="手機" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[templateNull].value">
            <lang locale="zh_CN" value="应用模板为空！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="應用範本為空！" />
            <lang locale="zh_TW" value="應用範本為空！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[template].value">
            <lang locale="zh_CN" value="更换模板后，所填信息将丢失？" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="更換範本後，所填信息將丟失？" />
            <lang locale="zh_TW" value="更換範本後，所填信息將丟失？" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[threeYear].value">
            <lang locale="zh_CN" value="近三年" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="近三年" />
            <lang locale="zh_TW" value="近三年" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[type].value">
            <lang locale="zh_CN" value="模板类型" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="範本類型" />
            <lang locale="zh_TW" value="範本類型" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unAuditTemplate].value">
            <lang locale="zh_CN" value="该模板已被引用，不能反审批！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="該範本已被引用，不能反審批！" />
            <lang locale="zh_TW" value="該範本已被引用，不能反審批！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unAudit].value">
            <lang locale="zh_CN" value="非审批状态不能反审批！" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="非審批狀態不能反審批！" />
            <lang locale="zh_TW" value="非審批狀態不能反審批！" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[unit].value">
            <lang locale="zh_CN" value="颁发单位" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="頒發單位" />
            <lang locale="zh_TW" value="頒發單位" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[update].value">
            <lang locale="zh_CN" value="更改为" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="更改為" />
            <lang locale="zh_TW" value="更改為" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[weight].value">
            <lang locale="zh_CN" value="权重" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="權重" />
            <lang locale="zh_TW" value="權重" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workClass].value">
            <lang locale="zh_CN" value="经营品牌" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="經營品牌" />
            <lang locale="zh_TW" value="經營品牌" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workPhone].value">
            <lang locale="zh_CN" value="办公电话" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="辦公電話" />
            <lang locale="zh_TW" value="辦公電話" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[workersAmount].value">
            <lang locale="zh_CN" value="劳务人员数量" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="勞務人員數量" />
            <lang locale="zh_TW" value="勞務人員數量" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[year].value">
            <lang locale="zh_CN" value="年份" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="年份" />
            <lang locale="zh_TW" value="年份" />
        </rs>
        <rs key="i18nResource[com.kingdee.eas.fdc.invite.supplier.SupplierResource].resourceItems.resourceItem[zhongBiao].value">
            <lang locale="zh_CN" value="中标" />
            <lang locale="en_US" value="value_new" />
            <lang locale="zh_HK" value="中標" />
            <lang locale="zh_TW" value="中標" />
        </rs>
    </resource>
</i18nResource>

